// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Represents a backfill job on a specific stream object.
public struct BackfillJob: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Output only. Backfill job state.
  public var state: BackfillJob.State = BackfillJob.State()

  /// Backfill job's triggering reason.
  public var trigger: BackfillJob.Trigger = BackfillJob.Trigger()

  /// Output only. Backfill job's start time.
  public var lastStartTime: GoogleWKT.Timestamp? = nil

  /// Output only. Backfill job's end time.
  public var lastEndTime: GoogleWKT.Timestamp? = nil

  /// Output only. Errors which caused the backfill job to fail.
  public var errors: [Error] = []

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `BackfillJob`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = BackfillJob().with { $0.state = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let state = CodingKeys(stringValue: "state")
    static let trigger = CodingKeys(stringValue: "trigger")
    static let lastStartTime = CodingKeys(stringValue: "lastStartTime")
    static let lastEndTime = CodingKeys(stringValue: "lastEndTime")
    static let errors = CodingKeys(stringValue: "errors")

    static let _knownKeys: Set<Swift.String> = [
      "state",
      "trigger",
      "lastStartTime",
      "lastEndTime",
      "errors",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(BackfillJob.State.self, forKey: .state) {
      self.state = value
    }
    if let value = try container.decodeIfPresent(BackfillJob.Trigger.self, forKey: .trigger) {
      self.trigger = value
    }
    self.lastStartTime = try container.decodeIfPresent(
      GoogleWKT.Timestamp.self, forKey: .lastStartTime)
    self.lastEndTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .lastEndTime)
    if let value = try container.decodeIfPresent([Error].self, forKey: .errors) {
      self.errors = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.state, forKey: .state)
    try container.encode(self.trigger, forKey: .trigger)
    try container.encodeIfPresent(self.lastStartTime, forKey: .lastStartTime)
    try container.encodeIfPresent(self.lastEndTime, forKey: .lastEndTime)
    try container.encode(self.errors, forKey: .errors)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// State of the stream object's backfill job.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum State: Codable, Equatable, Sendable {
    /// Default value.
    case unspecified
    /// Backfill job was never started for the stream object (stream has backfill
    /// strategy defined as manual or object was explicitly excluded from
    /// automatic backfill).
    case notStarted
    /// Backfill job will start pending available resources.
    case pending
    /// Backfill job is running.
    case active
    /// Backfill job stopped (next job run will start from beginning).
    case stopped
    /// Backfill job failed (due to an error).
    case failed
    /// Backfill completed successfully.
    case completed
    /// Backfill job failed since the table structure is currently unsupported
    /// for backfill.
    case unsupported
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .notStarted: return 1
      case .pending: return 2
      case .active: return 3
      case .stopped: return 4
      case .failed: return 5
      case .completed: return 6
      case .unsupported: return 7
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .notStarted: return "NOT_STARTED"
      case .pending: return "PENDING"
      case .active: return "ACTIVE"
      case .stopped: return "STOPPED"
      case .failed: return "FAILED"
      case .completed: return "COMPLETED"
      case .unsupported: return "UNSUPPORTED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "NOT_STARTED": self = .notStarted
      case "PENDING": self = .pending
      case "ACTIVE": self = .active
      case "STOPPED": self = .stopped
      case "FAILED": self = .failed
      case "COMPLETED": self = .completed
      case "UNSUPPORTED": self = .unsupported
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .notStarted
      case 2: self = .pending
      case 3: self = .active
      case 4: self = .stopped
      case 5: self = .failed
      case 6: self = .completed
      case 7: self = .unsupported
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATE_UNSPECIFIED")
      case .notStarted: return try container.encode("NOT_STARTED")
      case .pending: return try container.encode("PENDING")
      case .active: return try container.encode("ACTIVE")
      case .stopped: return try container.encode("STOPPED")
      case .failed: return try container.encode("FAILED")
      case .completed: return try container.encode("COMPLETED")
      case .unsupported: return try container.encode("UNSUPPORTED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Triggering reason for a backfill job.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Trigger: Codable, Equatable, Sendable {
    /// Default value.
    case unspecified
    /// Object backfill job was triggered automatically according to the stream's
    /// backfill strategy.
    case automatic
    /// Object backfill job was triggered manually using the dedicated API.
    case manual
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .automatic: return 1
      case .manual: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TRIGGER_UNSPECIFIED"
      case .automatic: return "AUTOMATIC"
      case .manual: return "MANUAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Trigger/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TRIGGER_UNSPECIFIED": self = .unspecified
      case "AUTOMATIC": self = .automatic
      case "MANUAL": self = .manual
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Trigger/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .automatic
      case 2: self = .manual
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("TRIGGER_UNSPECIFIED")
      case .automatic: return try container.encode("AUTOMATIC")
      case .manual: return try container.encode("MANUAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.BackfillJob"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
