// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

/// Datastream service
///
/// @Snippet(path: "DatastreamQuickstart")
public final class DatastreamClient: Clients.DatastreamProtocol, Sendable {
  let inner: any Clients.DatastreamStub
  let pollingErrorPolicy: GoogleCloudGax.PollingErrorPolicy
  let pollingBackoffPolicy: GoogleCloudGax.BackoffPolicy

  /// Creates a new `DatastreamClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.DatastreamStub = try Clients.DatastreamTransport(options)
    inner = Clients.DatastreamRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.DatastreamLogging(inner, logger: logger)
    }
    self.inner = inner
    self.pollingErrorPolicy = options.pollingErrorPolicy
    self.pollingBackoffPolicy = options.pollingBackoffPolicy
  }

  /// Use this method to list connection profiles created in a project and
  /// location.
  ///
  /// @Snippet(path: "Datastream_ListConnectionProfiles")
  public func listConnectionProfiles(
    request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse {
    try await self.inner.listConnectionProfiles(request: request, options: options)
  }

  /// Use this method to list connection profiles created in a project and
  /// location.
  ///
  /// @Snippet(path: "Datastream_ListConnectionProfiles")
  public func listConnectionProfiles(
    byItem: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listConnectionProfiles(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Use this method to get details about a connection profile.
  ///
  /// @Snippet(path: "Datastream_GetConnectionProfile")
  public func getConnectionProfile(
    request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile {
    try await self.inner.getConnectionProfile(request: request, options: options)
  }

  /// Use this method to create a connection profile in a project and location.
  ///
  /// @Snippet(path: "Datastream_CreateConnectionProfile")
  public func createConnectionProfile(
    request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createConnectionProfile(request: request, options: options)
  }

  /// Use this method to create a connection profile in a project and location.
  ///
  /// @Snippet(path: "Datastream_CreateConnectionProfile")
  public func createConnectionProfile(
    withPolling: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectionProfile>.State in
      return try op._extractStatus(ConnectionProfile.self)
    }
    let rawOp = try await self.createConnectionProfile(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectionProfile>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to update the parameters of a connection profile.
  ///
  /// @Snippet(path: "Datastream_UpdateConnectionProfile")
  public func updateConnectionProfile(
    request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateConnectionProfile(request: request, options: options)
  }

  /// Use this method to update the parameters of a connection profile.
  ///
  /// @Snippet(path: "Datastream_UpdateConnectionProfile")
  public func updateConnectionProfile(
    withPolling: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<ConnectionProfile>.State in
      return try op._extractStatus(ConnectionProfile.self)
    }
    let rawOp = try await self.updateConnectionProfile(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectionProfile>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to delete a connection profile.
  ///
  /// @Snippet(path: "Datastream_DeleteConnectionProfile")
  public func deleteConnectionProfile(
    request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteConnectionProfile(request: request, options: options)
  }

  /// Use this method to delete a connection profile.
  ///
  /// @Snippet(path: "Datastream_DeleteConnectionProfile")
  public func deleteConnectionProfile(
    withPolling: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteConnectionProfile(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to discover a connection profile.
  /// The discover API call exposes the data objects and metadata belonging to
  /// the profile. Typically, a request returns children data objects of a
  /// parent data object that's optionally supplied in the request.
  ///
  /// @Snippet(path: "Datastream_DiscoverConnectionProfile")
  public func discoverConnectionProfile(
    request: DiscoverConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse {
    try await self.inner.discoverConnectionProfile(request: request, options: options)
  }

  /// Use this method to list streams in a project and location.
  ///
  /// @Snippet(path: "Datastream_ListStreams")
  public func listStreams(
    request: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse {
    try await self.inner.listStreams(request: request, options: options)
  }

  /// Use this method to list streams in a project and location.
  ///
  /// @Snippet(path: "Datastream_ListStreams")
  public func listStreams(
    byItem: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Stream, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listStreams(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Use this method to get details about a stream.
  ///
  /// @Snippet(path: "Datastream_GetStream")
  public func getStream(
    request: GetStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.Stream {
    try await self.inner.getStream(request: request, options: options)
  }

  /// Use this method to create a stream.
  ///
  /// @Snippet(path: "Datastream_CreateStream")
  public func createStream(
    request: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createStream(request: request, options: options)
  }

  /// Use this method to create a stream.
  ///
  /// @Snippet(path: "Datastream_CreateStream")
  public func createStream(
    withPolling: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      return try op._extractStatus(Stream.self)
    }
    let rawOp = try await self.createStream(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to update the configuration of a stream.
  ///
  /// @Snippet(path: "Datastream_UpdateStream")
  public func updateStream(
    request: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.updateStream(request: request, options: options)
  }

  /// Use this method to update the configuration of a stream.
  ///
  /// @Snippet(path: "Datastream_UpdateStream")
  public func updateStream(
    withPolling: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      return try op._extractStatus(Stream.self)
    }
    let rawOp = try await self.updateStream(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to delete a stream.
  ///
  /// @Snippet(path: "Datastream_DeleteStream")
  public func deleteStream(
    request: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteStream(request: request, options: options)
  }

  /// Use this method to delete a stream.
  ///
  /// @Snippet(path: "Datastream_DeleteStream")
  public func deleteStream(
    withPolling: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteStream(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to start, resume or recover a stream with a non default CDC
  /// strategy.
  ///
  /// @Snippet(path: "Datastream_RunStream")
  public func runStream(
    request: RunStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.runStream(request: request, options: options)
  }

  /// Use this method to start, resume or recover a stream with a non default CDC
  /// strategy.
  ///
  /// @Snippet(path: "Datastream_RunStream")
  public func runStream(
    withPolling: RunStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      return try op._extractStatus(Stream.self)
    }
    let rawOp = try await self.runStream(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to get details about a stream object.
  ///
  /// @Snippet(path: "Datastream_GetStreamObject")
  public func getStreamObject(
    request: GetStreamObjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StreamObject {
    try await self.inner.getStreamObject(request: request, options: options)
  }

  /// Use this method to look up a stream object by its source object identifier.
  ///
  /// @Snippet(path: "Datastream_LookupStreamObject")
  public func lookupStreamObject(
    request: LookupStreamObjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StreamObject {
    try await self.inner.lookupStreamObject(request: request, options: options)
  }

  /// Use this method to list the objects of a specific stream.
  ///
  /// @Snippet(path: "Datastream_ListStreamObjects")
  public func listStreamObjects(
    request: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse {
    try await self.inner.listStreamObjects(request: request, options: options)
  }

  /// Use this method to list the objects of a specific stream.
  ///
  /// @Snippet(path: "Datastream_ListStreamObjects")
  public func listStreamObjects(
    byItem: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<StreamObject, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listStreamObjects(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Use this method to start a backfill job for the specified stream object.
  ///
  /// @Snippet(path: "Datastream_StartBackfillJob")
  public func startBackfillJob(
    request: StartBackfillJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse {
    try await self.inner.startBackfillJob(request: request, options: options)
  }

  /// Use this method to stop a backfill job for the specified stream object.
  ///
  /// @Snippet(path: "Datastream_StopBackfillJob")
  public func stopBackfillJob(
    request: StopBackfillJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse {
    try await self.inner.stopBackfillJob(request: request, options: options)
  }

  /// The FetchStaticIps API call exposes the static IP addresses used by
  /// Datastream.
  ///
  /// @Snippet(path: "Datastream_FetchStaticIps")
  public func fetchStaticIps(
    request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse {
    try await self.inner.fetchStaticIps(request: request, options: options)
  }

  /// Use this method to create a private connectivity configuration.
  ///
  /// @Snippet(path: "Datastream_CreatePrivateConnection")
  public func createPrivateConnection(
    request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createPrivateConnection(request: request, options: options)
  }

  /// Use this method to create a private connectivity configuration.
  ///
  /// @Snippet(path: "Datastream_CreatePrivateConnection")
  public func createPrivateConnection(
    withPolling: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<PrivateConnection> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<PrivateConnection>.State in
      return try op._extractStatus(PrivateConnection.self)
    }
    let rawOp = try await self.createPrivateConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<PrivateConnection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to get details about a private connectivity configuration.
  ///
  /// @Snippet(path: "Datastream_GetPrivateConnection")
  public func getPrivateConnection(
    request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.PrivateConnection {
    try await self.inner.getPrivateConnection(request: request, options: options)
  }

  /// Use this method to list private connectivity configurations in a project
  /// and location.
  ///
  /// @Snippet(path: "Datastream_ListPrivateConnections")
  public func listPrivateConnections(
    request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse {
    try await self.inner.listPrivateConnections(request: request, options: options)
  }

  /// Use this method to list private connectivity configurations in a project
  /// and location.
  ///
  /// @Snippet(path: "Datastream_ListPrivateConnections")
  public func listPrivateConnections(
    byItem: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<PrivateConnection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse
      in
      var request = byItem
      request.pageToken = token
      return try await self.listPrivateConnections(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Use this method to delete a private connectivity configuration.
  ///
  /// @Snippet(path: "Datastream_DeletePrivateConnection")
  public func deletePrivateConnection(
    request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deletePrivateConnection(request: request, options: options)
  }

  /// Use this method to delete a private connectivity configuration.
  ///
  /// @Snippet(path: "Datastream_DeletePrivateConnection")
  public func deletePrivateConnection(
    withPolling: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deletePrivateConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to create a route for a private connectivity configuration
  /// in a project and location.
  ///
  /// @Snippet(path: "Datastream_CreateRoute")
  public func createRoute(
    request: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.createRoute(request: request, options: options)
  }

  /// Use this method to create a route for a private connectivity configuration
  /// in a project and location.
  ///
  /// @Snippet(path: "Datastream_CreateRoute")
  public func createRoute(
    withPolling: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Route> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Route>.State
      in
      return try op._extractStatus(Route.self)
    }
    let rawOp = try await self.createRoute(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Route>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Use this method to get details about a route.
  ///
  /// @Snippet(path: "Datastream_GetRoute")
  public func getRoute(
    request: GetRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.Route {
    try await self.inner.getRoute(request: request, options: options)
  }

  /// Use this method to list routes created for a private connectivity
  /// configuration in a project and location.
  ///
  /// @Snippet(path: "Datastream_ListRoutes")
  public func listRoutes(
    request: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse {
    try await self.inner.listRoutes(request: request, options: options)
  }

  /// Use this method to list routes created for a private connectivity
  /// configuration in a project and location.
  ///
  /// @Snippet(path: "Datastream_ListRoutes")
  public func listRoutes(
    byItem: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Route, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listRoutes(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Use this method to delete a route.
  ///
  /// @Snippet(path: "Datastream_DeleteRoute")
  public func deleteRoute(
    request: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.deleteRoute(request: request, options: options)
  }

  /// Use this method to delete a route.
  ///
  /// @Snippet(path: "Datastream_DeleteRoute")
  public func deleteRoute(
    withPolling: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let extractStatus = {
      (op: GoogleLongRunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      return try op._extractStatusEmpty()
    }
    let rawOp = try await self.deleteRoute(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: initialState,
      polling: options.pollingErrorPolicy ?? self.pollingErrorPolicy,
      backoff: options.pollingBackoffPolicy ?? self.pollingBackoffPolicy,
      poll: poll,
    )
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Datastream_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "Datastream_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "Datastream_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Datastream_ListOperations")
  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Datastream_ListOperations")
  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Datastream_GetOperation")
  func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Datastream_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+OperationsClient
  ///
  /// @Snippet(path: "Datastream_CancelOperation")
  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `DatastreamClient`.
  ///
  /// To mock `DatastreamClient` change your functions to receive
  /// `some DatastreamProtocol` or `any DatastreamProtocol`
  /// and pass a mock implementation in your tests.
  public protocol DatastreamProtocol {
    /// See `DatastreamClient.listConnectionProfiles`.
    func listConnectionProfiles(request: ListConnectionProfilesRequest) async throws
      -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse

    /// See `DatastreamClient.listConnectionProfiles`.
    func listConnectionProfiles(
      byItem: ListConnectionProfilesRequest
    ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error>

    /// See `DatastreamClient.listConnectionProfiles`.
    func listConnectionProfiles(
      parent: Swift.String,
    ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error>

    /// See `DatastreamClient.getConnectionProfile`.
    func getConnectionProfile(request: GetConnectionProfileRequest) async throws
      -> GoogleCloudDatastreamV1.ConnectionProfile

    /// See `DatastreamClient.getConnectionProfile`.
    func getConnectionProfile(
      name: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile

    /// See `DatastreamClient.createConnectionProfile`.
    func createConnectionProfile(request: CreateConnectionProfileRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createConnectionProfile`.
    func createConnectionProfile(withPolling: CreateConnectionProfileRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectionProfile>

    /// See `DatastreamClient.createConnectionProfile`.
    func createConnectionProfile(
      parent: Swift.String,
      connectionProfile: ConnectionProfile?,
      connectionProfileId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile>

    /// See `DatastreamClient.updateConnectionProfile`.
    func updateConnectionProfile(request: UpdateConnectionProfileRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DatastreamClient.updateConnectionProfile`.
    func updateConnectionProfile(withPolling: UpdateConnectionProfileRequest) async throws
      -> any GoogleCloudGax.PollableOperation<ConnectionProfile>

    /// See `DatastreamClient.updateConnectionProfile`.
    func updateConnectionProfile(
      connectionProfile: ConnectionProfile?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile>

    /// See `DatastreamClient.deleteConnectionProfile`.
    func deleteConnectionProfile(request: DeleteConnectionProfileRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deleteConnectionProfile`.
    func deleteConnectionProfile(withPolling: DeleteConnectionProfileRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.deleteConnectionProfile`.
    func deleteConnectionProfile(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.discoverConnectionProfile`.
    func discoverConnectionProfile(request: DiscoverConnectionProfileRequest) async throws
      -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse

    /// See `DatastreamClient.listStreams`.
    func listStreams(request: ListStreamsRequest) async throws
      -> GoogleCloudDatastreamV1.ListStreamsResponse

    /// See `DatastreamClient.listStreams`.
    func listStreams(
      byItem: ListStreamsRequest
    ) throws -> any AsyncSequence<Stream, Swift.Error>

    /// See `DatastreamClient.listStreams`.
    func listStreams(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Stream, Swift.Error>

    /// See `DatastreamClient.getStream`.
    func getStream(request: GetStreamRequest) async throws -> GoogleCloudDatastreamV1.Stream

    /// See `DatastreamClient.getStream`.
    func getStream(
      name: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.Stream

    /// See `DatastreamClient.createStream`.
    func createStream(request: CreateStreamRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createStream`.
    func createStream(withPolling: CreateStreamRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Stream>

    /// See `DatastreamClient.createStream`.
    func createStream(
      parent: Swift.String,
      stream: Stream?,
      streamId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Stream>

    /// See `DatastreamClient.updateStream`.
    func updateStream(request: UpdateStreamRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.updateStream`.
    func updateStream(withPolling: UpdateStreamRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Stream>

    /// See `DatastreamClient.updateStream`.
    func updateStream(
      stream: Stream?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Stream>

    /// See `DatastreamClient.deleteStream`.
    func deleteStream(request: DeleteStreamRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deleteStream`.
    func deleteStream(withPolling: DeleteStreamRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `DatastreamClient.deleteStream`.
    func deleteStream(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.runStream`.
    func runStream(request: RunStreamRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.runStream`.
    func runStream(withPolling: RunStreamRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Stream>

    /// See `DatastreamClient.getStreamObject`.
    func getStreamObject(request: GetStreamObjectRequest) async throws
      -> GoogleCloudDatastreamV1.StreamObject

    /// See `DatastreamClient.getStreamObject`.
    func getStreamObject(
      name: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.StreamObject

    /// See `DatastreamClient.lookupStreamObject`.
    func lookupStreamObject(request: LookupStreamObjectRequest) async throws
      -> GoogleCloudDatastreamV1.StreamObject

    /// See `DatastreamClient.listStreamObjects`.
    func listStreamObjects(request: ListStreamObjectsRequest) async throws
      -> GoogleCloudDatastreamV1.ListStreamObjectsResponse

    /// See `DatastreamClient.listStreamObjects`.
    func listStreamObjects(
      byItem: ListStreamObjectsRequest
    ) throws -> any AsyncSequence<StreamObject, Swift.Error>

    /// See `DatastreamClient.listStreamObjects`.
    func listStreamObjects(
      parent: Swift.String,
    ) throws -> any AsyncSequence<StreamObject, Swift.Error>

    /// See `DatastreamClient.startBackfillJob`.
    func startBackfillJob(request: StartBackfillJobRequest) async throws
      -> GoogleCloudDatastreamV1.StartBackfillJobResponse

    /// See `DatastreamClient.startBackfillJob`.
    func startBackfillJob(
      object: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse

    /// See `DatastreamClient.stopBackfillJob`.
    func stopBackfillJob(request: StopBackfillJobRequest) async throws
      -> GoogleCloudDatastreamV1.StopBackfillJobResponse

    /// See `DatastreamClient.stopBackfillJob`.
    func stopBackfillJob(
      object: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse

    /// See `DatastreamClient.fetchStaticIps`.
    func fetchStaticIps(request: FetchStaticIpsRequest) async throws
      -> GoogleCloudDatastreamV1.FetchStaticIpsResponse

    /// See `DatastreamClient.fetchStaticIps`.
    func fetchStaticIps(
      name: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse

    /// See `DatastreamClient.createPrivateConnection`.
    func createPrivateConnection(request: CreatePrivateConnectionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createPrivateConnection`.
    func createPrivateConnection(withPolling: CreatePrivateConnectionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<PrivateConnection>

    /// See `DatastreamClient.createPrivateConnection`.
    func createPrivateConnection(
      parent: Swift.String,
      privateConnection: PrivateConnection?,
      privateConnectionId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<PrivateConnection>

    /// See `DatastreamClient.getPrivateConnection`.
    func getPrivateConnection(request: GetPrivateConnectionRequest) async throws
      -> GoogleCloudDatastreamV1.PrivateConnection

    /// See `DatastreamClient.getPrivateConnection`.
    func getPrivateConnection(
      name: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.PrivateConnection

    /// See `DatastreamClient.listPrivateConnections`.
    func listPrivateConnections(request: ListPrivateConnectionsRequest) async throws
      -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse

    /// See `DatastreamClient.listPrivateConnections`.
    func listPrivateConnections(
      byItem: ListPrivateConnectionsRequest
    ) throws -> any AsyncSequence<PrivateConnection, Swift.Error>

    /// See `DatastreamClient.listPrivateConnections`.
    func listPrivateConnections(
      parent: Swift.String,
    ) throws -> any AsyncSequence<PrivateConnection, Swift.Error>

    /// See `DatastreamClient.deletePrivateConnection`.
    func deletePrivateConnection(request: DeletePrivateConnectionRequest) async throws
      -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deletePrivateConnection`.
    func deletePrivateConnection(withPolling: DeletePrivateConnectionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.deletePrivateConnection`.
    func deletePrivateConnection(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.createRoute`.
    func createRoute(request: CreateRouteRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createRoute`.
    func createRoute(withPolling: CreateRouteRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Route>

    /// See `DatastreamClient.createRoute`.
    func createRoute(
      parent: Swift.String,
      route: Route?,
      routeId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Route>

    /// See `DatastreamClient.getRoute`.
    func getRoute(request: GetRouteRequest) async throws -> GoogleCloudDatastreamV1.Route

    /// See `DatastreamClient.getRoute`.
    func getRoute(
      name: Swift.String,
    ) async throws -> GoogleCloudDatastreamV1.Route

    /// See `DatastreamClient.listRoutes`.
    func listRoutes(request: ListRoutesRequest) async throws
      -> GoogleCloudDatastreamV1.ListRoutesResponse

    /// See `DatastreamClient.listRoutes`.
    func listRoutes(
      byItem: ListRoutesRequest
    ) throws -> any AsyncSequence<Route, Swift.Error>

    /// See `DatastreamClient.listRoutes`.
    func listRoutes(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Route, Swift.Error>

    /// See `DatastreamClient.deleteRoute`.
    func deleteRoute(request: DeleteRouteRequest) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deleteRoute`.
    func deleteRoute(withPolling: DeleteRouteRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Swift.Void>

    /// See `DatastreamClient.deleteRoute`.
    func deleteRoute(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `DatastreamClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DatastreamClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `DatastreamClient.listOperations`.
    func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
      -> GoogleLongRunning.ListOperationsResponse

    /// See `DatastreamClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DatastreamClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DatastreamClient.deleteOperation`.
    func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws

    /// See `DatastreamClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `DatastreamClient.cancelOperation`.
    func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws

    /// See `DatastreamClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `DatastreamClient.listConnectionProfiles`.
    func listConnectionProfiles(
      request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse

    /// See `DatastreamClient.listConnectionProfiles`.
    func listConnectionProfiles(
      byItem: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error>

    /// See `DatastreamClient.getConnectionProfile`.
    func getConnectionProfile(
      request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile

    /// See `DatastreamClient.createConnectionProfile`.
    func createConnectionProfile(
      request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createConnectionProfile`.
    func createConnectionProfile(
      withPolling: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile>

    /// See `DatastreamClient.updateConnectionProfile`.
    func updateConnectionProfile(
      request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.updateConnectionProfile`.
    func updateConnectionProfile(
      withPolling: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile>

    /// See `DatastreamClient.deleteConnectionProfile`.
    func deleteConnectionProfile(
      request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deleteConnectionProfile`.
    func deleteConnectionProfile(
      withPolling: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.discoverConnectionProfile`.
    func discoverConnectionProfile(
      request: DiscoverConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse

    /// See `DatastreamClient.listStreams`.
    func listStreams(
      request: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse

    /// See `DatastreamClient.listStreams`.
    func listStreams(
      byItem: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Stream, Swift.Error>

    /// See `DatastreamClient.getStream`.
    func getStream(
      request: GetStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.Stream

    /// See `DatastreamClient.createStream`.
    func createStream(
      request: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createStream`.
    func createStream(
      withPolling: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Stream>

    /// See `DatastreamClient.updateStream`.
    func updateStream(
      request: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.updateStream`.
    func updateStream(
      withPolling: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Stream>

    /// See `DatastreamClient.deleteStream`.
    func deleteStream(
      request: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deleteStream`.
    func deleteStream(
      withPolling: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.runStream`.
    func runStream(
      request: RunStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.runStream`.
    func runStream(
      withPolling: RunStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Stream>

    /// See `DatastreamClient.getStreamObject`.
    func getStreamObject(
      request: GetStreamObjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StreamObject

    /// See `DatastreamClient.lookupStreamObject`.
    func lookupStreamObject(
      request: LookupStreamObjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StreamObject

    /// See `DatastreamClient.listStreamObjects`.
    func listStreamObjects(
      request: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse

    /// See `DatastreamClient.listStreamObjects`.
    func listStreamObjects(
      byItem: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<StreamObject, Swift.Error>

    /// See `DatastreamClient.startBackfillJob`.
    func startBackfillJob(
      request: StartBackfillJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse

    /// See `DatastreamClient.stopBackfillJob`.
    func stopBackfillJob(
      request: StopBackfillJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse

    /// See `DatastreamClient.fetchStaticIps`.
    func fetchStaticIps(
      request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse

    /// See `DatastreamClient.createPrivateConnection`.
    func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createPrivateConnection`.
    func createPrivateConnection(
      withPolling: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<PrivateConnection>

    /// See `DatastreamClient.getPrivateConnection`.
    func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.PrivateConnection

    /// See `DatastreamClient.listPrivateConnections`.
    func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse

    /// See `DatastreamClient.listPrivateConnections`.
    func listPrivateConnections(
      byItem: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<PrivateConnection, Swift.Error>

    /// See `DatastreamClient.deletePrivateConnection`.
    func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deletePrivateConnection`.
    func deletePrivateConnection(
      withPolling: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.createRoute`.
    func createRoute(
      request: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.createRoute`.
    func createRoute(
      withPolling: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Route>

    /// See `DatastreamClient.getRoute`.
    func getRoute(
      request: GetRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.Route

    /// See `DatastreamClient.listRoutes`.
    func listRoutes(
      request: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse

    /// See `DatastreamClient.listRoutes`.
    func listRoutes(
      byItem: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Route, Swift.Error>

    /// See `DatastreamClient.deleteRoute`.
    func deleteRoute(
      request: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    /// See `DatastreamClient.deleteRoute`.
    func deleteRoute(
      withPolling: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void>

    /// See `DatastreamClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `DatastreamClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `DatastreamClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `DatastreamClient.listOperations`.
    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    /// See `DatastreamClient.listOperations`.
    func listOperations(
      byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error>

    /// See `DatastreamClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `DatastreamClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.DatastreamProtocol {
  public func listConnectionProfiles(request: ListConnectionProfilesRequest) async throws
    -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse
  {
    try await self.listConnectionProfiles(request: request, options: .init())
  }

  public func listConnectionProfiles(
    request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listConnectionProfiles(
    byItem: ListConnectionProfilesRequest
  ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error> {
    try self.listConnectionProfiles(byItem: byItem, options: .init())
  }

  public func listConnectionProfiles(
    byItem: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listConnectionProfiles(
    parent: Swift.String,
  ) throws -> any AsyncSequence<ConnectionProfile, Swift.Error> {
    let request = ListConnectionProfilesRequest().with {
      $0.parent = parent
    }
    return try self.listConnectionProfiles(byItem: request)
  }

  public func getConnectionProfile(request: GetConnectionProfileRequest) async throws
    -> GoogleCloudDatastreamV1.ConnectionProfile
  {
    try await self.getConnectionProfile(request: request, options: .init())
  }

  public func getConnectionProfile(
    request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getConnectionProfile(
    name: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile {
    let request = GetConnectionProfileRequest().with {
      $0.name = name
    }
    return try await self.getConnectionProfile(request: request)
  }

  public func createConnectionProfile(request: CreateConnectionProfileRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createConnectionProfile(request: request, options: .init())
  }

  public func createConnectionProfile(
    request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createConnectionProfile(withPolling: CreateConnectionProfileRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectionProfile>
  {
    try await self.createConnectionProfile(withPolling: withPolling, options: .init())
  }

  public func createConnectionProfile(
    withPolling: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectionProfile>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createConnectionProfile(
    parent: Swift.String,
    connectionProfile: ConnectionProfile?,
    connectionProfileId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile> {
    let request = CreateConnectionProfileRequest().with {
      $0.parent = parent
      $0.connectionProfile = connectionProfile
      $0.connectionProfileId = connectionProfileId
    }
    return try await self.createConnectionProfile(withPolling: request)
  }

  public func updateConnectionProfile(request: UpdateConnectionProfileRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.updateConnectionProfile(request: request, options: .init())
  }

  public func updateConnectionProfile(
    request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateConnectionProfile(withPolling: UpdateConnectionProfileRequest) async throws
    -> any GoogleCloudGax.PollableOperation<ConnectionProfile>
  {
    try await self.updateConnectionProfile(withPolling: withPolling, options: .init())
  }

  public func updateConnectionProfile(
    withPolling: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<ConnectionProfile>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateConnectionProfile(
    connectionProfile: ConnectionProfile?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<ConnectionProfile> {
    let request = UpdateConnectionProfileRequest().with {
      $0.connectionProfile = connectionProfile
      $0.updateMask = updateMask
    }
    return try await self.updateConnectionProfile(withPolling: request)
  }

  public func deleteConnectionProfile(request: DeleteConnectionProfileRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deleteConnectionProfile(request: request, options: .init())
  }

  public func deleteConnectionProfile(
    request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteConnectionProfile(withPolling: DeleteConnectionProfileRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deleteConnectionProfile(withPolling: withPolling, options: .init())
  }

  public func deleteConnectionProfile(
    withPolling: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteConnectionProfile(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteConnectionProfileRequest().with {
      $0.name = name
    }
    return try await self.deleteConnectionProfile(withPolling: request)
  }

  public func discoverConnectionProfile(request: DiscoverConnectionProfileRequest) async throws
    -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse
  {
    try await self.discoverConnectionProfile(request: request, options: .init())
  }

  public func discoverConnectionProfile(
    request: DiscoverConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listStreams(request: ListStreamsRequest) async throws
    -> GoogleCloudDatastreamV1.ListStreamsResponse
  {
    try await self.listStreams(request: request, options: .init())
  }

  public func listStreams(
    request: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listStreams(
    byItem: ListStreamsRequest
  ) throws -> any AsyncSequence<Stream, Swift.Error> {
    try self.listStreams(byItem: byItem, options: .init())
  }

  public func listStreams(
    byItem: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Stream, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listStreams(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Stream, Swift.Error> {
    let request = ListStreamsRequest().with {
      $0.parent = parent
    }
    return try self.listStreams(byItem: request)
  }

  public func getStream(request: GetStreamRequest) async throws -> GoogleCloudDatastreamV1.Stream {
    try await self.getStream(request: request, options: .init())
  }

  public func getStream(
    request: GetStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.Stream {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getStream(
    name: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.Stream {
    let request = GetStreamRequest().with {
      $0.name = name
    }
    return try await self.getStream(request: request)
  }

  public func createStream(request: CreateStreamRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.createStream(request: request, options: .init())
  }

  public func createStream(
    request: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createStream(withPolling: CreateStreamRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Stream>
  {
    try await self.createStream(withPolling: withPolling, options: .init())
  }

  public func createStream(
    withPolling: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createStream(
    parent: Swift.String,
    stream: Stream?,
    streamId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let request = CreateStreamRequest().with {
      $0.parent = parent
      $0.stream = stream
      $0.streamId = streamId
    }
    return try await self.createStream(withPolling: request)
  }

  public func updateStream(request: UpdateStreamRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.updateStream(request: request, options: .init())
  }

  public func updateStream(
    request: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateStream(withPolling: UpdateStreamRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Stream>
  {
    try await self.updateStream(withPolling: withPolling, options: .init())
  }

  public func updateStream(
    withPolling: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateStream(
    stream: Stream?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let request = UpdateStreamRequest().with {
      $0.stream = stream
      $0.updateMask = updateMask
    }
    return try await self.updateStream(withPolling: request)
  }

  public func deleteStream(request: DeleteStreamRequest) async throws -> GoogleLongRunning.Operation
  {
    try await self.deleteStream(request: request, options: .init())
  }

  public func deleteStream(
    request: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteStream(withPolling: DeleteStreamRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteStream(withPolling: withPolling, options: .init())
  }

  public func deleteStream(
    withPolling: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteStream(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteStreamRequest().with {
      $0.name = name
    }
    return try await self.deleteStream(withPolling: request)
  }

  public func runStream(request: RunStreamRequest) async throws -> GoogleLongRunning.Operation {
    try await self.runStream(request: request, options: .init())
  }

  public func runStream(
    request: RunStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func runStream(withPolling: RunStreamRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Stream>
  {
    try await self.runStream(withPolling: withPolling, options: .init())
  }

  public func runStream(
    withPolling: RunStreamRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Stream> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Stream>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getStreamObject(request: GetStreamObjectRequest) async throws
    -> GoogleCloudDatastreamV1.StreamObject
  {
    try await self.getStreamObject(request: request, options: .init())
  }

  public func getStreamObject(
    request: GetStreamObjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StreamObject {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getStreamObject(
    name: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.StreamObject {
    let request = GetStreamObjectRequest().with {
      $0.name = name
    }
    return try await self.getStreamObject(request: request)
  }

  public func lookupStreamObject(request: LookupStreamObjectRequest) async throws
    -> GoogleCloudDatastreamV1.StreamObject
  {
    try await self.lookupStreamObject(request: request, options: .init())
  }

  public func lookupStreamObject(
    request: LookupStreamObjectRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StreamObject {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listStreamObjects(request: ListStreamObjectsRequest) async throws
    -> GoogleCloudDatastreamV1.ListStreamObjectsResponse
  {
    try await self.listStreamObjects(request: request, options: .init())
  }

  public func listStreamObjects(
    request: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listStreamObjects(
    byItem: ListStreamObjectsRequest
  ) throws -> any AsyncSequence<StreamObject, Swift.Error> {
    try self.listStreamObjects(byItem: byItem, options: .init())
  }

  public func listStreamObjects(
    byItem: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<StreamObject, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listStreamObjects(
    parent: Swift.String,
  ) throws -> any AsyncSequence<StreamObject, Swift.Error> {
    let request = ListStreamObjectsRequest().with {
      $0.parent = parent
    }
    return try self.listStreamObjects(byItem: request)
  }

  public func startBackfillJob(request: StartBackfillJobRequest) async throws
    -> GoogleCloudDatastreamV1.StartBackfillJobResponse
  {
    try await self.startBackfillJob(request: request, options: .init())
  }

  public func startBackfillJob(
    request: StartBackfillJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func startBackfillJob(
    object: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse {
    let request = StartBackfillJobRequest().with {
      $0.object = object
    }
    return try await self.startBackfillJob(request: request)
  }

  public func stopBackfillJob(request: StopBackfillJobRequest) async throws
    -> GoogleCloudDatastreamV1.StopBackfillJobResponse
  {
    try await self.stopBackfillJob(request: request, options: .init())
  }

  public func stopBackfillJob(
    request: StopBackfillJobRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func stopBackfillJob(
    object: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse {
    let request = StopBackfillJobRequest().with {
      $0.object = object
    }
    return try await self.stopBackfillJob(request: request)
  }

  public func fetchStaticIps(request: FetchStaticIpsRequest) async throws
    -> GoogleCloudDatastreamV1.FetchStaticIpsResponse
  {
    try await self.fetchStaticIps(request: request, options: .init())
  }

  public func fetchStaticIps(
    request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func fetchStaticIps(
    name: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse {
    let request = FetchStaticIpsRequest().with {
      $0.name = name
    }
    return try await self.fetchStaticIps(request: request)
  }

  public func createPrivateConnection(request: CreatePrivateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.createPrivateConnection(request: request, options: .init())
  }

  public func createPrivateConnection(
    request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createPrivateConnection(withPolling: CreatePrivateConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<PrivateConnection>
  {
    try await self.createPrivateConnection(withPolling: withPolling, options: .init())
  }

  public func createPrivateConnection(
    withPolling: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<PrivateConnection> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<PrivateConnection>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createPrivateConnection(
    parent: Swift.String,
    privateConnection: PrivateConnection?,
    privateConnectionId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<PrivateConnection> {
    let request = CreatePrivateConnectionRequest().with {
      $0.parent = parent
      $0.privateConnection = privateConnection
      $0.privateConnectionId = privateConnectionId
    }
    return try await self.createPrivateConnection(withPolling: request)
  }

  public func getPrivateConnection(request: GetPrivateConnectionRequest) async throws
    -> GoogleCloudDatastreamV1.PrivateConnection
  {
    try await self.getPrivateConnection(request: request, options: .init())
  }

  public func getPrivateConnection(
    request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.PrivateConnection {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getPrivateConnection(
    name: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.PrivateConnection {
    let request = GetPrivateConnectionRequest().with {
      $0.name = name
    }
    return try await self.getPrivateConnection(request: request)
  }

  public func listPrivateConnections(request: ListPrivateConnectionsRequest) async throws
    -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse
  {
    try await self.listPrivateConnections(request: request, options: .init())
  }

  public func listPrivateConnections(
    request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listPrivateConnections(
    byItem: ListPrivateConnectionsRequest
  ) throws -> any AsyncSequence<PrivateConnection, Swift.Error> {
    try self.listPrivateConnections(byItem: byItem, options: .init())
  }

  public func listPrivateConnections(
    byItem: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<PrivateConnection, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse
      in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listPrivateConnections(
    parent: Swift.String,
  ) throws -> any AsyncSequence<PrivateConnection, Swift.Error> {
    let request = ListPrivateConnectionsRequest().with {
      $0.parent = parent
    }
    return try self.listPrivateConnections(byItem: request)
  }

  public func deletePrivateConnection(request: DeletePrivateConnectionRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.deletePrivateConnection(request: request, options: .init())
  }

  public func deletePrivateConnection(
    request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deletePrivateConnection(withPolling: DeletePrivateConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Swift.Void>
  {
    try await self.deletePrivateConnection(withPolling: withPolling, options: .init())
  }

  public func deletePrivateConnection(
    withPolling: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deletePrivateConnection(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeletePrivateConnectionRequest().with {
      $0.name = name
    }
    return try await self.deletePrivateConnection(withPolling: request)
  }

  public func createRoute(request: CreateRouteRequest) async throws -> GoogleLongRunning.Operation {
    try await self.createRoute(request: request, options: .init())
  }

  public func createRoute(
    request: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createRoute(withPolling: CreateRouteRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Route>
  {
    try await self.createRoute(withPolling: withPolling, options: .init())
  }

  public func createRoute(
    withPolling: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Route> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Route>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createRoute(
    parent: Swift.String,
    route: Route?,
    routeId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Route> {
    let request = CreateRouteRequest().with {
      $0.parent = parent
      $0.route = route
      $0.routeId = routeId
    }
    return try await self.createRoute(withPolling: request)
  }

  public func getRoute(request: GetRouteRequest) async throws -> GoogleCloudDatastreamV1.Route {
    try await self.getRoute(request: request, options: .init())
  }

  public func getRoute(
    request: GetRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.Route {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getRoute(
    name: Swift.String,
  ) async throws -> GoogleCloudDatastreamV1.Route {
    let request = GetRouteRequest().with {
      $0.name = name
    }
    return try await self.getRoute(request: request)
  }

  public func listRoutes(request: ListRoutesRequest) async throws
    -> GoogleCloudDatastreamV1.ListRoutesResponse
  {
    try await self.listRoutes(request: request, options: .init())
  }

  public func listRoutes(
    request: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listRoutes(
    byItem: ListRoutesRequest
  ) throws -> any AsyncSequence<Route, Swift.Error> {
    try self.listRoutes(byItem: byItem, options: .init())
  }

  public func listRoutes(
    byItem: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Route, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listRoutes(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Route, Swift.Error> {
    let request = ListRoutesRequest().with {
      $0.parent = parent
    }
    return try self.listRoutes(byItem: request)
  }

  public func deleteRoute(request: DeleteRouteRequest) async throws -> GoogleLongRunning.Operation {
    try await self.deleteRoute(request: request, options: .init())
  }

  public func deleteRoute(
    request: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteRoute(withPolling: DeleteRouteRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Swift.Void>
  {
    try await self.deleteRoute(withPolling: withPolling, options: .init())
  }

  public func deleteRoute(
    withPolling: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Swift.Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteRoute(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Swift.Void> {
    let request = DeleteRouteRequest().with {
      $0.name = name
    }
    return try await self.deleteRoute(withPolling: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongRunning.ListOperationsRequest) async throws
    -> GoogleLongRunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleLongRunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongRunning.Operation, Swift.Error> {
    let request = GoogleLongRunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongRunning.GetOperationRequest) async throws
    -> GoogleLongRunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongRunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongRunning.Operation {
    let request = GoogleLongRunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongRunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongRunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongRunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
