// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleCloudWKT
import GoogleLongRunning
import GoogleRpc
@_spi(GoogleCloudInternal) import GoogleCloudGax

extension Clients {
  final class DatastreamTransport: DatastreamStub {
    let inner: GoogleCloudGax._HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax._HTTPClient(
        from: options,
        withDefaultEndpoint: "https://datastream.googleapis.com",
      )
    }

    public func listConnectionProfiles(
      request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/connectionProfiles"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.ListConnectionProfilesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getConnectionProfile(
      request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/connectionProfiles/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/connectionProfiles/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/connectionProfiles/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.ConnectionProfile.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createConnectionProfile(
      request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/connectionProfiles"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(
              request.connectionProfileId, prefix: "connectionProfileId"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          query.append(contentsOf: try encoder.encode(request.force, prefix: "force"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.connectionProfile {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateConnectionProfile(
      request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.connectionProfile.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/connectionProfiles/"), .singleWildcard,
              ],
              fieldName: "connection_profile.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          query.append(contentsOf: try encoder.encode(request.force, prefix: "force"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.connectionProfile.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/connectionProfiles/"), .singleWildcard,
            ],
            fieldName: "connection_profile.name",
            expecting: "projects/*/locations/*/connectionProfiles/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.connectionProfile {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteConnectionProfile(
      request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/connectionProfiles/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/connectionProfiles/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/connectionProfiles/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func discoverConnectionProfile(
      request: DiscoverConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/connectionProfiles:discover"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse.self,
        timeout: options.attemptTimeout
      ).get()
    }

    public func listStreams(
      request: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/streams"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.ListStreamsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getStream(
      request: GetStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.Stream {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/streams/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.Stream.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createStream(
      request: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/streams"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.streamId, prefix: "streamId"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          query.append(contentsOf: try encoder.encode(request.force, prefix: "force"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.stream {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func updateStream(
      request: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.stream.map({ $0.name }),
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard,
              ],
              fieldName: "stream.name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          query.append(contentsOf: try encoder.encode(request.force, prefix: "force"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.PATCH) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.stream.map({ $0.name }),
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard,
            ],
            fieldName: "stream.name",
            expecting: "projects/*/locations/*/streams/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.stream {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteStream(
      request: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/streams/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func runStream(
      request: RunStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):run"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/streams/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getStreamObject(
      request: GetStreamObjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StreamObject {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard, .literal("/objects/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard, .literal("/objects/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/streams/*/objects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.StreamObject.self, timeout: options.attemptTimeout
      ).get()
    }

    public func lookupStreamObject(
      request: LookupStreamObjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StreamObject {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/objects:lookup"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/streams/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudDatastreamV1.StreamObject.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listStreamObjects(
      request: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/objects"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/streams/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.ListStreamObjectsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func startBackfillJob(
      request: StartBackfillJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.object as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard, .literal("/objects/"), .singleWildcard,
              ],
              fieldName: "object")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):startBackfillJob"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.object as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard, .literal("/objects/"), .singleWildcard,
            ],
            fieldName: "object",
            expecting: "projects/*/locations/*/streams/*/objects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudDatastreamV1.StartBackfillJobResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func stopBackfillJob(
      request: StopBackfillJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.object as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/streams/"), .singleWildcard, .literal("/objects/"), .singleWildcard,
              ],
              fieldName: "object")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):stopBackfillJob"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.object as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/streams/"), .singleWildcard, .literal("/objects/"), .singleWildcard,
            ],
            fieldName: "object",
            expecting: "projects/*/locations/*/streams/*/objects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      return try await req.rpc(
        GoogleCloudDatastreamV1.StopBackfillJobResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func fetchStaticIps(
      request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):fetchStaticIps"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.FetchStaticIpsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/privateConnections"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(
            contentsOf: try encoder.encode(
              request.privateConnectionId, prefix: "privateConnectionId"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          query.append(contentsOf: try encoder.encode(request.force, prefix: "force"))
          query.append(contentsOf: try encoder.encode(request.validateOnly, prefix: "validateOnly"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.privateConnection {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.PrivateConnection {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/privateConnections/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/privateConnections/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/privateConnections/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.PrivateConnection.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/privateConnections"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.ListPrivateConnectionsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/privateConnections/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          query.append(contentsOf: try encoder.encode(request.force, prefix: "force"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/privateConnections/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/privateConnections/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func createRoute(
      request: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/privateConnections/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/routes"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.routeId, prefix: "routeId"))
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/privateConnections/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/privateConnections/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      if let body = request.route {
        try req.setBody(json: body)
      }
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getRoute(
      request: GetRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.Route {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/privateConnections/"), .singleWildcard, .literal("/routes/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/privateConnections/"), .singleWildcard, .literal("/routes/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/privateConnections/*/routes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.Route.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listRoutes(
      request: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.parent as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/privateConnections/"), .singleWildcard,
              ],
              fieldName: "parent")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/routes"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.orderBy, prefix: "orderBy"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.parent as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/privateConnections/"), .singleWildcard,
            ],
            fieldName: "parent",
            expecting: "projects/*/locations/*/privateConnections/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudDatastreamV1.ListRoutesResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteRoute(
      request: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/privateConnections/"), .singleWildcard, .literal("/routes/"),
                .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.requestId, prefix: "requestId"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/privateConnections/"), .singleWildcard, .literal("/routes/"),
              .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/privateConnections/*/routes/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [.literal("projects/"), .singleWildcard],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/locations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [.literal("projects/"), .singleWildcard],
            fieldName: "name",
            expecting: "projects/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.ListLocationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleCloudLocation.Location.self, timeout: options.attemptTimeout
      ).get()
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)/operations"
          var query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          let encoder = GoogleCloudGax._QueryParameterEncoder()
          query.append(contentsOf: try encoder.encode(request.filter, prefix: "filter"))
          query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
          query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
          query.append(
            contentsOf: try encoder.encode(
              request.returnPartialSuccess, prefix: "returnPartialSuccess"))
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.ListOperationsResponse.self, timeout: options.attemptTimeout
      ).get()
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.GET) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      return try await req.rpc(
        GoogleLongRunning.Operation.self, timeout: options.attemptTimeout
      ).get()
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0)"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.DELETE) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      let (path, query, configure) = try {
        () throws -> (
          Swift.String, [URLQueryItem], (inout GoogleCloudGax._HTTPClientRequest) -> Void
        ) in
        if let candidate = try { () throws -> (Swift.String, [URLQueryItem])? in
          guard
            let pathVariable0 = try GoogleCloudGax._RoutingMatcher.pathValue(
              request.name as Swift.String?,
              matching: [
                .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
                .literal("/operations/"), .singleWildcard,
              ],
              fieldName: "name")
          else {
            return nil
          }
          let path = "/v1/\(pathVariable0):cancel"
          let query = [
            URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
          ]
          return (path, query)
        }() {
          return (candidate.0, candidate.1, { $0.setMethod(.POST) })
        }
        var paths: [GoogleCloudGax.PathMismatch] = []
        do {
          var builder = GoogleCloudGax._PathMismatchBuilder()
          builder.maybeAdd(
            request.name as Swift.String?,
            matching: [
              .literal("projects/"), .singleWildcard, .literal("/locations/"), .singleWildcard,
              .literal("/operations/"), .singleWildcard,
            ],
            fieldName: "name",
            expecting: "projects/*/locations/*/operations/*"
          )
          paths.append(builder.build())
        }
        throw GoogleCloudGax.RequestError.binding(GoogleCloudGax.BindingError(paths: paths))
      }()
      var req = try await self.inner.newRequest(
        percentEncodedPath: path, query: query, options: options)
      configure(&req)
      req.addHeader(name: GoogleCloudGax._HeaderNames.apiClient, value: Clients.clientHeader)
      try req.setBody(json: request)
      _ = try await req.rpc(
        GoogleCloudWKT.Empty.self, timeout: options.attemptTimeout
      ).get()
    }
  }
}
