// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongRunning
import GoogleRpc
import GoogleCloudGax

extension Clients {
  protocol DatastreamStub: Sendable {
    func listConnectionProfiles(
      request: ListConnectionProfilesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListConnectionProfilesResponse

    func getConnectionProfile(
      request: GetConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ConnectionProfile

    func createConnectionProfile(
      request: CreateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateConnectionProfile(
      request: UpdateConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteConnectionProfile(
      request: DeleteConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func discoverConnectionProfile(
      request: DiscoverConnectionProfileRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.DiscoverConnectionProfileResponse

    func listStreams(
      request: ListStreamsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListStreamsResponse

    func getStream(
      request: GetStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.Stream

    func createStream(
      request: CreateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func updateStream(
      request: UpdateStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteStream(
      request: DeleteStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func runStream(
      request: RunStreamRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getStreamObject(
      request: GetStreamObjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StreamObject

    func lookupStreamObject(
      request: LookupStreamObjectRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StreamObject

    func listStreamObjects(
      request: ListStreamObjectsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListStreamObjectsResponse

    func startBackfillJob(
      request: StartBackfillJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StartBackfillJobResponse

    func stopBackfillJob(
      request: StopBackfillJobRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.StopBackfillJobResponse

    func fetchStaticIps(
      request: FetchStaticIpsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.FetchStaticIpsResponse

    func createPrivateConnection(
      request: CreatePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getPrivateConnection(
      request: GetPrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.PrivateConnection

    func listPrivateConnections(
      request: ListPrivateConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListPrivateConnectionsResponse

    func deletePrivateConnection(
      request: DeletePrivateConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func createRoute(
      request: CreateRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func getRoute(
      request: GetRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.Route

    func listRoutes(
      request: ListRoutesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudDatastreamV1.ListRoutesResponse

    func deleteRoute(
      request: DeleteRouteRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse

    func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation

    func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}
