// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The configuration of the stream destination.
public struct DestinationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Destination connection profile resource.
  /// Format: `projects/{project}/locations/{location}/connectionProfiles/{name}`
  public var destinationConnectionProfile: Swift.String = Swift.String()

  /// Stream configuration that is specific to the data destination type.
  public var destinationStreamConfig: OneOf_DestinationStreamConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `DestinationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DestinationConfig().with { $0.destinationConnectionProfile = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let destinationConnectionProfile = CodingKeys(
      stringValue: "destinationConnectionProfile")
    static let gcsDestinationConfig = CodingKeys(stringValue: "gcsDestinationConfig")
    static let bigqueryDestinationConfig = CodingKeys(stringValue: "bigqueryDestinationConfig")

    static let _knownKeys: Set<Swift.String> = [
      "destinationConnectionProfile",
      "gcsDestinationConfig",
      "bigqueryDestinationConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .destinationConnectionProfile)
    {
      self.destinationConnectionProfile = value
    }

    var destinationStreamConfig: OneOf_DestinationStreamConfig? = nil
    let destinationStreamConfigCheckAndSet = {
      if destinationStreamConfig != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'destinationStreamConfig'"))
      }
      destinationStreamConfig = $0
    }
    if let gcsDestinationConfig = try container.decodeIfPresent(
      GcsDestinationConfig?.self, forKey: .gcsDestinationConfig)
    {
      try destinationStreamConfigCheckAndSet(.gcsDestinationConfig(gcsDestinationConfig))
    }
    if let bigqueryDestinationConfig = try container.decodeIfPresent(
      BigQueryDestinationConfig?.self, forKey: .bigqueryDestinationConfig)
    {
      try destinationStreamConfigCheckAndSet(.bigqueryDestinationConfig(bigqueryDestinationConfig))
    }
    self.destinationStreamConfig = destinationStreamConfig
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.destinationConnectionProfile, forKey: .destinationConnectionProfile)

    if let choice = self.destinationStreamConfig {
      switch choice {
      case .gcsDestinationConfig(let value):
        try container.encode(value, forKey: .gcsDestinationConfig)
      case .bigqueryDestinationConfig(let value):
        try container.encode(value, forKey: .bigqueryDestinationConfig)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Stream configuration that is specific to the data destination type.
  public enum OneOf_DestinationStreamConfig: Codable, Equatable, Sendable {
    /// A configuration for how data should be loaded to Cloud Storage.
    indirect case gcsDestinationConfig(GcsDestinationConfig?)
    /// BigQuery destination configuration.
    indirect case bigqueryDestinationConfig(BigQueryDestinationConfig?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.DestinationConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
