// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Response from a discover request.
public struct DiscoverConnectionProfileResponse: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The data object that has been enriched by the discover API call.
  public var dataObject: OneOf_DataObject? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `DiscoverConnectionProfileResponse`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = DiscoverConnectionProfileResponse().with { $0.oracleRdbms = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let oracleRdbms = CodingKeys(stringValue: "oracleRdbms")
    static let mysqlRdbms = CodingKeys(stringValue: "mysqlRdbms")
    static let postgresqlRdbms = CodingKeys(stringValue: "postgresqlRdbms")
    static let sqlServerRdbms = CodingKeys(stringValue: "sqlServerRdbms")
    static let salesforceOrg = CodingKeys(stringValue: "salesforceOrg")
    static let mongodbCluster = CodingKeys(stringValue: "mongodbCluster")

    static let _knownKeys: Set<Swift.String> = [
      "oracleRdbms",
      "mysqlRdbms",
      "postgresqlRdbms",
      "sqlServerRdbms",
      "salesforceOrg",
      "mongodbCluster",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var dataObject: OneOf_DataObject? = nil
    let dataObjectCheckAndSet = {
      if dataObject != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'dataObject'"))
      }
      dataObject = $0
    }
    if let oracleRdbms = try container.decodeIfPresent(OracleRdbms?.self, forKey: .oracleRdbms) {
      try dataObjectCheckAndSet(.oracleRdbms(oracleRdbms))
    }
    if let mysqlRdbms = try container.decodeIfPresent(MysqlRdbms?.self, forKey: .mysqlRdbms) {
      try dataObjectCheckAndSet(.mysqlRdbms(mysqlRdbms))
    }
    if let postgresqlRdbms = try container.decodeIfPresent(
      PostgresqlRdbms?.self, forKey: .postgresqlRdbms)
    {
      try dataObjectCheckAndSet(.postgresqlRdbms(postgresqlRdbms))
    }
    if let sqlServerRdbms = try container.decodeIfPresent(
      SqlServerRdbms?.self, forKey: .sqlServerRdbms)
    {
      try dataObjectCheckAndSet(.sqlServerRdbms(sqlServerRdbms))
    }
    if let salesforceOrg = try container.decodeIfPresent(
      SalesforceOrg?.self, forKey: .salesforceOrg)
    {
      try dataObjectCheckAndSet(.salesforceOrg(salesforceOrg))
    }
    if let mongodbCluster = try container.decodeIfPresent(
      MongodbCluster?.self, forKey: .mongodbCluster)
    {
      try dataObjectCheckAndSet(.mongodbCluster(mongodbCluster))
    }
    self.dataObject = dataObject
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.dataObject {
      switch choice {
      case .oracleRdbms(let value):
        try container.encode(value, forKey: .oracleRdbms)
      case .mysqlRdbms(let value):
        try container.encode(value, forKey: .mysqlRdbms)
      case .postgresqlRdbms(let value):
        try container.encode(value, forKey: .postgresqlRdbms)
      case .sqlServerRdbms(let value):
        try container.encode(value, forKey: .sqlServerRdbms)
      case .salesforceOrg(let value):
        try container.encode(value, forKey: .salesforceOrg)
      case .mongodbCluster(let value):
        try container.encode(value, forKey: .mongodbCluster)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// The data object that has been enriched by the discover API call.
  public enum OneOf_DataObject: Codable, Equatable, Sendable {
    /// Enriched Oracle RDBMS object.
    indirect case oracleRdbms(OracleRdbms?)
    /// Enriched MySQL RDBMS object.
    indirect case mysqlRdbms(MysqlRdbms?)
    /// Enriched PostgreSQL RDBMS object.
    indirect case postgresqlRdbms(PostgresqlRdbms?)
    /// Enriched SQLServer RDBMS object.
    indirect case sqlServerRdbms(SqlServerRdbms?)
    /// Enriched Salesforce organization.
    indirect case salesforceOrg(SalesforceOrg?)
    /// Enriched MongoDB cluster.
    indirect case mongodbCluster(MongodbCluster?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.DiscoverConnectionProfileResponse"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
