// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Forward SSH Tunnel connectivity.
public struct ForwardSshTunnelConnectivity: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Hostname for the SSH tunnel.
  public var hostname: Swift.String = Swift.String()

  /// Required. Username for the SSH tunnel.
  public var username: Swift.String = Swift.String()

  /// Port for the SSH tunnel, default value is 22.
  public var port: Swift.Int32 = Swift.Int32()

  public var authenticationMethod: OneOf_AuthenticationMethod? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `ForwardSshTunnelConnectivity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ForwardSshTunnelConnectivity().with { $0.hostname = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hostname = CodingKeys(stringValue: "hostname")
    static let username = CodingKeys(stringValue: "username")
    static let port = CodingKeys(stringValue: "port")
    static let password = CodingKeys(stringValue: "password")
    static let privateKey = CodingKeys(stringValue: "privateKey")

    static let _knownKeys: Set<Swift.String> = [
      "hostname",
      "username",
      "port",
      "password",
      "privateKey",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostname) {
      self.hostname = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
      self.username = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }

    var authenticationMethod: OneOf_AuthenticationMethod? = nil
    let authenticationMethodCheckAndSet = {
      if authenticationMethod != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authenticationMethod'"))
      }
      authenticationMethod = $0
    }
    if let password = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      try authenticationMethodCheckAndSet(.password(password))
    }
    if let privateKey = try container.decodeIfPresent(Swift.String.self, forKey: .privateKey) {
      try authenticationMethodCheckAndSet(.privateKey(privateKey))
    }
    self.authenticationMethod = authenticationMethod
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.port, forKey: .port)

    if let choice = self.authenticationMethod {
      switch choice {
      case .password(let value):
        try container.encode(value, forKey: .password)
      case .privateKey(let value):
        try container.encode(value, forKey: .privateKey)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public enum OneOf_AuthenticationMethod: Codable, Equatable, Sendable {
    /// Input only. SSH password.
    case password(Swift.String)
    /// Input only. SSH private key.
    case privateKey(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.ForwardSshTunnelConnectivity"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
