// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Forward SSH Tunnel connectivity.
public struct ForwardSshTunnelConnectivity: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. Hostname for the SSH tunnel.
  public var hostname: Swift.String = Swift.String()

  /// Required. Username for the SSH tunnel.
  public var username: Swift.String = Swift.String()

  /// Port for the SSH tunnel, default value is 22.
  public var port: Swift.Int32 = Swift.Int32()

  public var authenticationMethod: OneOf_AuthenticationMethod? = nil

  /// Initialize a new instance of `ForwardSshTunnelConnectivity`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = ForwardSshTunnelConnectivity().with { $0.hostname = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case hostname = "hostname"
    case username = "username"
    case port = "port"
    case password = "password"
    case privateKey = "privateKey"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.hostname = try container.decode(Swift.String.self, forKey: .hostname)
    self.username = try container.decode(Swift.String.self, forKey: .username)
    self.port = try container.decode(Swift.Int32.self, forKey: .port)

    var authenticationMethod: OneOf_AuthenticationMethod? = nil
    let authenticationMethodCheckAndSet = {
      if authenticationMethod != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'authenticationMethod'"))
      }
      authenticationMethod = $0
    }
    if let password = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      try authenticationMethodCheckAndSet(.password(password))
    }
    if let privateKey = try container.decodeIfPresent(Swift.String.self, forKey: .privateKey) {
      try authenticationMethodCheckAndSet(.privateKey(privateKey))
    }
    self.authenticationMethod = authenticationMethod
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.port, forKey: .port)

    if let choice = self.authenticationMethod {
      switch choice {
      case .password(let value):
        try container.encode(value, forKey: .password)
      case .privateKey(let value):
        try container.encode(value, forKey: .privateKey)
      }
    }
  }

  public enum OneOf_AuthenticationMethod: Codable, Equatable, Sendable {
    /// Input only. SSH password.
    case password(Swift.String)
    /// Input only. SSH private key.
    case privateKey(Swift.String)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.ForwardSshTunnelConnectivity"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
