// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Google Cloud Storage destination configuration
public struct GcsDestinationConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Path inside the Cloud Storage bucket to write data to.
  public var path: Swift.String = Swift.String()

  /// The maximum file size to be saved in the bucket.
  public var fileRotationMb: Swift.Int32 = Swift.Int32()

  /// The maximum duration for which new events are added before a file is
  /// closed and a new file is created. Values within the range of 15-60 seconds
  /// are allowed.
  public var fileRotationInterval: GoogleCloudWKT.Duration? = nil

  /// File Format that the data should be written in.
  public var fileFormat: OneOf_FileFormat? = nil

  /// Initialize a new instance of `GcsDestinationConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = GcsDestinationConfig().with { $0.path = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case path = "path"
    case fileRotationMb = "fileRotationMb"
    case fileRotationInterval = "fileRotationInterval"
    case avroFileFormat = "avroFileFormat"
    case jsonFileFormat = "jsonFileFormat"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.path = try container.decode(Swift.String.self, forKey: .path)
    self.fileRotationMb = try container.decode(Swift.Int32.self, forKey: .fileRotationMb)
    self.fileRotationInterval = try container.decodeIfPresent(
      GoogleCloudWKT.Duration.self, forKey: .fileRotationInterval)

    var fileFormat: OneOf_FileFormat? = nil
    let fileFormatCheckAndSet = {
      if fileFormat != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'fileFormat'"))
      }
      fileFormat = $0
    }
    if let avroFileFormat = try container.decodeIfPresent(
      AvroFileFormat?.self, forKey: .avroFileFormat)
    {
      try fileFormatCheckAndSet(.avroFileFormat(avroFileFormat))
    }
    if let jsonFileFormat = try container.decodeIfPresent(
      JsonFileFormat?.self, forKey: .jsonFileFormat)
    {
      try fileFormatCheckAndSet(.jsonFileFormat(jsonFileFormat))
    }
    self.fileFormat = fileFormat
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.path, forKey: .path)
    try container.encode(self.fileRotationMb, forKey: .fileRotationMb)
    try container.encode(self.fileRotationInterval, forKey: .fileRotationInterval)

    if let choice = self.fileFormat {
      switch choice {
      case .avroFileFormat(let value):
        try container.encode(value, forKey: .avroFileFormat)
      case .jsonFileFormat(let value):
        try container.encode(value, forKey: .jsonFileFormat)
      }
    }
  }

  /// File Format that the data should be written in.
  public enum OneOf_FileFormat: Codable, Equatable, Sendable {
    /// AVRO file format configuration.
    indirect case avroFileFormat(AvroFileFormat?)
    /// JSON file format configuration.
    indirect case jsonFileFormat(JsonFileFormat?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.GcsDestinationConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
