// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// MongoDB profile.
public struct MongodbProfile: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. List of host addresses for a MongoDB cluster.
  /// For SRV connection format, this list must contain exactly one DNS host
  /// without a port. For Standard connection format, this list must contain all
  /// the required hosts in the cluster with their respective ports.
  public var hostAddresses: [HostAddress] = []

  /// Optional. Name of the replica set. Only needed for self hosted replica set
  /// type MongoDB cluster. For SRV connection format, this field must be empty.
  /// For Standard connection format, this field must be specified.
  public var replicaSet: Swift.String = Swift.String()

  /// Required. Username for the MongoDB connection.
  public var username: Swift.String = Swift.String()

  /// Optional. Password for the MongoDB connection. Mutually exclusive with the
  /// `secret_manager_stored_password` field.
  public var password: Swift.String = Swift.String()

  /// Optional. A reference to a Secret Manager resource name storing the
  /// SQLServer connection password. Mutually exclusive with the `password`
  /// field.
  public var secretManagerStoredPassword: Swift.String = Swift.String()

  /// Optional. SSL configuration for the MongoDB connection.
  public var sslConfig: MongodbSslConfig? = nil

  /// MongoDB connection format.
  /// Must specify either srv_connection_format or standard_connection_format.
  public var mongodbConnectionFormat: OneOf_MongodbConnectionFormat? = nil

  /// Initialize a new instance of `MongodbProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MongodbProfile().with { $0.hostAddresses = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case hostAddresses = "hostAddresses"
    case replicaSet = "replicaSet"
    case username = "username"
    case password = "password"
    case secretManagerStoredPassword = "secretManagerStoredPassword"
    case sslConfig = "sslConfig"
    case srvConnectionFormat = "srvConnectionFormat"
    case standardConnectionFormat = "standardConnectionFormat"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.hostAddresses = try container.decode([HostAddress].self, forKey: .hostAddresses)
    self.replicaSet = try container.decode(Swift.String.self, forKey: .replicaSet)
    self.username = try container.decode(Swift.String.self, forKey: .username)
    self.password = try container.decode(Swift.String.self, forKey: .password)
    self.secretManagerStoredPassword = try container.decode(
      Swift.String.self, forKey: .secretManagerStoredPassword)
    self.sslConfig = try container.decodeIfPresent(MongodbSslConfig.self, forKey: .sslConfig)

    var mongodbConnectionFormat: OneOf_MongodbConnectionFormat? = nil
    let mongodbConnectionFormatCheckAndSet = {
      if mongodbConnectionFormat != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'mongodbConnectionFormat'"))
      }
      mongodbConnectionFormat = $0
    }
    if let srvConnectionFormat = try container.decodeIfPresent(
      SrvConnectionFormat?.self, forKey: .srvConnectionFormat)
    {
      try mongodbConnectionFormatCheckAndSet(.srvConnectionFormat(srvConnectionFormat))
    }
    if let standardConnectionFormat = try container.decodeIfPresent(
      StandardConnectionFormat?.self, forKey: .standardConnectionFormat)
    {
      try mongodbConnectionFormatCheckAndSet(.standardConnectionFormat(standardConnectionFormat))
    }
    self.mongodbConnectionFormat = mongodbConnectionFormat
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostAddresses, forKey: .hostAddresses)
    try container.encode(self.replicaSet, forKey: .replicaSet)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.password, forKey: .password)
    try container.encode(self.secretManagerStoredPassword, forKey: .secretManagerStoredPassword)
    try container.encode(self.sslConfig, forKey: .sslConfig)

    if let choice = self.mongodbConnectionFormat {
      switch choice {
      case .srvConnectionFormat(let value):
        try container.encode(value, forKey: .srvConnectionFormat)
      case .standardConnectionFormat(let value):
        try container.encode(value, forKey: .standardConnectionFormat)
      }
    }
  }

  /// MongoDB connection format.
  /// Must specify either srv_connection_format or standard_connection_format.
  public enum OneOf_MongodbConnectionFormat: Codable, Equatable, Sendable {
    /// Srv connection format.
    indirect case srvConnectionFormat(SrvConnectionFormat?)
    /// Standard connection format.
    indirect case standardConnectionFormat(StandardConnectionFormat?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.MongodbProfile"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
