// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// MySQL SSL configuration information.
public struct MysqlSslConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Optional. Input only. PEM-encoded private key associated with the Client
  /// Certificate. If this field is used then the 'client_certificate' and the
  /// 'ca_certificate' fields are mandatory.
  public var clientKey: Swift.String = Swift.String()

  /// Output only. Indicates whether the client_key field is set.
  public var clientKeySet: Swift.Bool = Swift.Bool()

  /// Optional. Input only. PEM-encoded certificate that will be used by the
  /// replica to authenticate against the source database server. If this field
  /// is used then the 'client_key' and the 'ca_certificate' fields are
  /// mandatory.
  public var clientCertificate: Swift.String = Swift.String()

  /// Output only. Indicates whether the client_certificate field is set.
  public var clientCertificateSet: Swift.Bool = Swift.Bool()

  /// Input only. PEM-encoded certificate of the CA that signed the source
  /// database server's certificate.
  public var caCertificate: Swift.String = Swift.String()

  /// Output only. Indicates whether the ca_certificate field is set.
  public var caCertificateSet: Swift.Bool = Swift.Bool()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `MysqlSslConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MysqlSslConfig().with { $0.clientKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let clientKey = CodingKeys(stringValue: "clientKey")
    static let clientKeySet = CodingKeys(stringValue: "clientKeySet")
    static let clientCertificate = CodingKeys(stringValue: "clientCertificate")
    static let clientCertificateSet = CodingKeys(stringValue: "clientCertificateSet")
    static let caCertificate = CodingKeys(stringValue: "caCertificate")
    static let caCertificateSet = CodingKeys(stringValue: "caCertificateSet")

    static let _knownKeys: Set<Swift.String> = [
      "clientKey",
      "clientKeySet",
      "clientCertificate",
      "clientCertificateSet",
      "caCertificate",
      "caCertificateSet",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientKey) {
      self.clientKey = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .clientKeySet) {
      self.clientKeySet = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientCertificate) {
      self.clientCertificate = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .clientCertificateSet) {
      self.clientCertificateSet = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .caCertificate) {
      self.caCertificate = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .caCertificateSet) {
      self.caCertificateSet = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.clientKey, forKey: .clientKey)
    try container.encode(self.clientKeySet, forKey: .clientKeySet)
    try container.encode(self.clientCertificate, forKey: .clientCertificate)
    try container.encode(self.clientCertificateSet, forKey: .clientCertificateSet)
    try container.encode(self.caCertificate, forKey: .caCertificate)
    try container.encode(self.caCertificateSet, forKey: .caCertificateSet)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.MysqlSslConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
