// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// MySQL SSL configuration information.
public struct MysqlSslConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Optional. Input only. PEM-encoded private key associated with the Client
  /// Certificate. If this field is used then the 'client_certificate' and the
  /// 'ca_certificate' fields are mandatory.
  public var clientKey: Swift.String = Swift.String()

  /// Output only. Indicates whether the client_key field is set.
  public var clientKeySet: Swift.Bool = Swift.Bool()

  /// Optional. Input only. PEM-encoded certificate that will be used by the
  /// replica to authenticate against the source database server. If this field
  /// is used then the 'client_key' and the 'ca_certificate' fields are
  /// mandatory.
  public var clientCertificate: Swift.String = Swift.String()

  /// Output only. Indicates whether the client_certificate field is set.
  public var clientCertificateSet: Swift.Bool = Swift.Bool()

  /// Input only. PEM-encoded certificate of the CA that signed the source
  /// database server's certificate.
  public var caCertificate: Swift.String = Swift.String()

  /// Output only. Indicates whether the ca_certificate field is set.
  public var caCertificateSet: Swift.Bool = Swift.Bool()

  /// Initialize a new instance of `MysqlSslConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = MysqlSslConfig().with { $0.clientKey = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.MysqlSslConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
