// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Oracle Column.
public struct OracleColumn: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Column name.
  public var column: Swift.String = Swift.String()

  /// The Oracle data type.
  public var dataType: Swift.String = Swift.String()

  /// Column length.
  public var length: Swift.Int32 = Swift.Int32()

  /// Column precision.
  public var precision: Swift.Int32 = Swift.Int32()

  /// Column scale.
  public var scale: Swift.Int32 = Swift.Int32()

  /// Column encoding.
  public var encoding: Swift.String = Swift.String()

  /// Whether or not the column represents a primary key.
  public var primaryKey: Swift.Bool = Swift.Bool()

  /// Whether or not the column can accept a null value.
  public var nullable: Swift.Bool = Swift.Bool()

  /// The ordinal position of the column in the table.
  public var ordinalPosition: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `OracleColumn`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OracleColumn().with { $0.column = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.OracleColumn"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
