// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Oracle SSL configuration information.
public struct OracleSslConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Input only. PEM-encoded certificate of the CA that signed the source
  /// database server's certificate.
  public var caCertificate: Swift.String = Swift.String()

  /// Output only. Indicates whether the ca_certificate field has been set for
  /// this Connection-Profile.
  public var caCertificateSet: Swift.Bool = Swift.Bool()

  /// Optional. The distinguished name (DN) mentioned in the server
  /// certificate. This corresponds to SSL_SERVER_CERT_DN sqlnet parameter.
  /// Refer
  /// https://docs.oracle.com/en/database/oracle/oracle-database/19/netrf/local-naming-parameters-in-tns-ora-file.html#GUID-70AB0695-A9AA-4A94-B141-4C605236EEB7
  /// If this field is not provided, the DN matching is not enforced.
  public var serverCertificateDistinguishedName: Swift.String = Swift.String()

  /// Initialize a new instance of `OracleSslConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OracleSslConfig().with { $0.caCertificate = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.OracleSslConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
