// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// Oracle data source configuration
public struct OracleSourceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Oracle objects to include in the stream.
  public var includeObjects: OracleRdbms? = nil

  /// Oracle objects to exclude from the stream.
  public var excludeObjects: OracleRdbms? = nil

  /// Maximum number of concurrent CDC tasks. The number should be non-negative.
  /// If not set (or set to 0), the system's default value is used.
  public var maxConcurrentCdcTasks: Swift.Int32 = Swift.Int32()

  /// Maximum number of concurrent backfill tasks. The number should be
  /// non-negative. If not set (or set to 0), the system's default value is used.
  public var maxConcurrentBackfillTasks: Swift.Int32 = Swift.Int32()

  /// The configuration for handle Oracle large objects.
  public var largeObjectsHandling: OneOf_LargeObjectsHandling? = nil

  /// Configuration to select the CDC method.
  public var cdcMethod: OneOf_CdcMethod? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OracleSourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OracleSourceConfig().with { $0.includeObjects = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let includeObjects = CodingKeys(stringValue: "includeObjects")
    static let excludeObjects = CodingKeys(stringValue: "excludeObjects")
    static let maxConcurrentCdcTasks = CodingKeys(stringValue: "maxConcurrentCdcTasks")
    static let maxConcurrentBackfillTasks = CodingKeys(stringValue: "maxConcurrentBackfillTasks")
    static let dropLargeObjects = CodingKeys(stringValue: "dropLargeObjects")
    static let streamLargeObjects = CodingKeys(stringValue: "streamLargeObjects")
    static let logMiner = CodingKeys(stringValue: "logMiner")
    static let binaryLogParser = CodingKeys(stringValue: "binaryLogParser")

    static let _knownKeys: Set<Swift.String> = [
      "includeObjects",
      "excludeObjects",
      "maxConcurrentCdcTasks",
      "maxConcurrentBackfillTasks",
      "dropLargeObjects",
      "streamLargeObjects",
      "logMiner",
      "binaryLogParser",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.includeObjects = try container.decodeIfPresent(OracleRdbms.self, forKey: .includeObjects)
    self.excludeObjects = try container.decodeIfPresent(OracleRdbms.self, forKey: .excludeObjects)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .maxConcurrentCdcTasks) {
      self.maxConcurrentCdcTasks = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .maxConcurrentBackfillTasks)
    {
      self.maxConcurrentBackfillTasks = value
    }

    var largeObjectsHandling: OneOf_LargeObjectsHandling? = nil
    let largeObjectsHandlingCheckAndSet = {
      if largeObjectsHandling != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'largeObjectsHandling'"))
      }
      largeObjectsHandling = $0
    }
    if let dropLargeObjects = try container.decodeIfPresent(
      OracleSourceConfig.DropLargeObjects?.self, forKey: .dropLargeObjects)
    {
      try largeObjectsHandlingCheckAndSet(.dropLargeObjects(dropLargeObjects))
    }
    if let streamLargeObjects = try container.decodeIfPresent(
      OracleSourceConfig.StreamLargeObjects?.self, forKey: .streamLargeObjects)
    {
      try largeObjectsHandlingCheckAndSet(.streamLargeObjects(streamLargeObjects))
    }
    self.largeObjectsHandling = largeObjectsHandling

    var cdcMethod: OneOf_CdcMethod? = nil
    let cdcMethodCheckAndSet = {
      if cdcMethod != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'cdcMethod'"))
      }
      cdcMethod = $0
    }
    if let logMiner = try container.decodeIfPresent(
      OracleSourceConfig.LogMiner?.self, forKey: .logMiner)
    {
      try cdcMethodCheckAndSet(.logMiner(logMiner))
    }
    if let binaryLogParser = try container.decodeIfPresent(
      OracleSourceConfig.BinaryLogParser?.self, forKey: .binaryLogParser)
    {
      try cdcMethodCheckAndSet(.binaryLogParser(binaryLogParser))
    }
    self.cdcMethod = cdcMethod
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.includeObjects, forKey: .includeObjects)
    try container.encodeIfPresent(self.excludeObjects, forKey: .excludeObjects)
    try container.encode(self.maxConcurrentCdcTasks, forKey: .maxConcurrentCdcTasks)
    try container.encode(self.maxConcurrentBackfillTasks, forKey: .maxConcurrentBackfillTasks)

    if let choice = self.largeObjectsHandling {
      switch choice {
      case .dropLargeObjects(let value):
        try container.encode(value, forKey: .dropLargeObjects)
      case .streamLargeObjects(let value):
        try container.encode(value, forKey: .streamLargeObjects)
      }
    }

    if let choice = self.cdcMethod {
      switch choice {
      case .logMiner(let value):
        try container.encode(value, forKey: .logMiner)
      case .binaryLogParser(let value):
        try container.encode(value, forKey: .binaryLogParser)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration to drop large object values.
  public struct DropLargeObjects: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `DropLargeObjects`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DropLargeObjects().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.DropLargeObjects"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to stream large object values.
  public struct StreamLargeObjects: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StreamLargeObjects`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StreamLargeObjects().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.StreamLargeObjects"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to use LogMiner CDC method.
  public struct LogMiner: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LogMiner`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LogMiner().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let _knownKeys: Set<Swift.String> = []
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.LogMiner"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to use Binary Log Parser CDC technique.
  public struct BinaryLogParser: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Configuration to specify how the log file should be accessed.
    public var logFileAccess: OneOf_LogFileAccess? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `BinaryLogParser`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BinaryLogParser().with { $0.oracleAsmLogFileAccess = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let oracleAsmLogFileAccess = CodingKeys(stringValue: "oracleAsmLogFileAccess")
      static let logFileDirectories = CodingKeys(stringValue: "logFileDirectories")

      static let _knownKeys: Set<Swift.String> = [
        "oracleAsmLogFileAccess",
        "logFileDirectories",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var logFileAccess: OneOf_LogFileAccess? = nil
      let logFileAccessCheckAndSet = {
        if logFileAccess != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'logFileAccess'"))
        }
        logFileAccess = $0
      }
      if let oracleAsmLogFileAccess = try container.decodeIfPresent(
        OracleSourceConfig.BinaryLogParser.OracleAsmLogFileAccess?.self,
        forKey: .oracleAsmLogFileAccess)
      {
        try logFileAccessCheckAndSet(.oracleAsmLogFileAccess(oracleAsmLogFileAccess))
      }
      if let logFileDirectories = try container.decodeIfPresent(
        OracleSourceConfig.BinaryLogParser.LogFileDirectories?.self, forKey: .logFileDirectories)
      {
        try logFileAccessCheckAndSet(.logFileDirectories(logFileDirectories))
      }
      self.logFileAccess = logFileAccess
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.logFileAccess {
        switch choice {
        case .oracleAsmLogFileAccess(let value):
          try container.encode(value, forKey: .oracleAsmLogFileAccess)
        case .logFileDirectories(let value):
          try container.encode(value, forKey: .logFileDirectories)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Configuration to use Oracle ASM to access the log files.
    public struct OracleAsmLogFileAccess: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `OracleAsmLogFileAccess`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = OracleAsmLogFileAccess().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let _knownKeys: Set<Swift.String> = []
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.BinaryLogParser.OracleAsmLogFileAccess"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration to specify the Oracle directories to access the log files.
    public struct LogFileDirectories: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Required. Oracle directory for online logs.
      public var onlineLogDirectory: Swift.String = Swift.String()

      /// Required. Oracle directory for archived logs.
      public var archivedLogDirectory: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `LogFileDirectories`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LogFileDirectories().with { $0.onlineLogDirectory = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let onlineLogDirectory = CodingKeys(stringValue: "onlineLogDirectory")
        static let archivedLogDirectory = CodingKeys(stringValue: "archivedLogDirectory")

        static let _knownKeys: Set<Swift.String> = [
          "onlineLogDirectory",
          "archivedLogDirectory",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .onlineLogDirectory)
        {
          self.onlineLogDirectory = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .archivedLogDirectory)
        {
          self.archivedLogDirectory = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.onlineLogDirectory, forKey: .onlineLogDirectory)
        try container.encode(self.archivedLogDirectory, forKey: .archivedLogDirectory)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.BinaryLogParser.LogFileDirectories"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration to specify how the log file should be accessed.
    public enum OneOf_LogFileAccess: Codable, Equatable, Sendable {
      /// Use Oracle ASM.
      indirect case oracleAsmLogFileAccess(
        OracleSourceConfig.BinaryLogParser.OracleAsmLogFileAccess?)
      /// Use Oracle directories.
      indirect case logFileDirectories(OracleSourceConfig.BinaryLogParser.LogFileDirectories?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.BinaryLogParser"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The configuration for handle Oracle large objects.
  public enum OneOf_LargeObjectsHandling: Codable, Equatable, Sendable {
    /// Drop large object values.
    indirect case dropLargeObjects(OracleSourceConfig.DropLargeObjects?)
    /// Stream large object values.
    indirect case streamLargeObjects(OracleSourceConfig.StreamLargeObjects?)
  }

  /// Configuration to select the CDC method.
  public enum OneOf_CdcMethod: Codable, Equatable, Sendable {
    /// Use LogMiner.
    indirect case logMiner(OracleSourceConfig.LogMiner?)
    /// Use Binary Log Parser.
    indirect case binaryLogParser(OracleSourceConfig.BinaryLogParser?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
