// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Oracle data source configuration
public struct OracleSourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Oracle objects to include in the stream.
  public var includeObjects: OracleRdbms? = nil

  /// Oracle objects to exclude from the stream.
  public var excludeObjects: OracleRdbms? = nil

  /// Maximum number of concurrent CDC tasks. The number should be non-negative.
  /// If not set (or set to 0), the system's default value is used.
  public var maxConcurrentCdcTasks: Swift.Int32 = Swift.Int32()

  /// Maximum number of concurrent backfill tasks. The number should be
  /// non-negative. If not set (or set to 0), the system's default value is used.
  public var maxConcurrentBackfillTasks: Swift.Int32 = Swift.Int32()

  /// The configuration for handle Oracle large objects.
  public var largeObjectsHandling: OneOf_LargeObjectsHandling? = nil

  /// Configuration to select the CDC method.
  public var cdcMethod: OneOf_CdcMethod? = nil

  /// Initialize a new instance of `OracleSourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OracleSourceConfig().with { $0.includeObjects = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case includeObjects = "includeObjects"
    case excludeObjects = "excludeObjects"
    case maxConcurrentCdcTasks = "maxConcurrentCdcTasks"
    case maxConcurrentBackfillTasks = "maxConcurrentBackfillTasks"
    case dropLargeObjects = "dropLargeObjects"
    case streamLargeObjects = "streamLargeObjects"
    case logMiner = "logMiner"
    case binaryLogParser = "binaryLogParser"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.includeObjects = try container.decodeIfPresent(OracleRdbms.self, forKey: .includeObjects)
    self.excludeObjects = try container.decodeIfPresent(OracleRdbms.self, forKey: .excludeObjects)
    self.maxConcurrentCdcTasks = try container.decode(
      Swift.Int32.self, forKey: .maxConcurrentCdcTasks)
    self.maxConcurrentBackfillTasks = try container.decode(
      Swift.Int32.self, forKey: .maxConcurrentBackfillTasks)

    var largeObjectsHandling: OneOf_LargeObjectsHandling? = nil
    let largeObjectsHandlingCheckAndSet = {
      if largeObjectsHandling != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'largeObjectsHandling'"))
      }
      largeObjectsHandling = $0
    }
    if let dropLargeObjects = try container.decodeIfPresent(
      OracleSourceConfig.DropLargeObjects?.self, forKey: .dropLargeObjects)
    {
      try largeObjectsHandlingCheckAndSet(.dropLargeObjects(dropLargeObjects))
    }
    if let streamLargeObjects = try container.decodeIfPresent(
      OracleSourceConfig.StreamLargeObjects?.self, forKey: .streamLargeObjects)
    {
      try largeObjectsHandlingCheckAndSet(.streamLargeObjects(streamLargeObjects))
    }
    self.largeObjectsHandling = largeObjectsHandling

    var cdcMethod: OneOf_CdcMethod? = nil
    let cdcMethodCheckAndSet = {
      if cdcMethod != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'cdcMethod'"))
      }
      cdcMethod = $0
    }
    if let logMiner = try container.decodeIfPresent(
      OracleSourceConfig.LogMiner?.self, forKey: .logMiner)
    {
      try cdcMethodCheckAndSet(.logMiner(logMiner))
    }
    if let binaryLogParser = try container.decodeIfPresent(
      OracleSourceConfig.BinaryLogParser?.self, forKey: .binaryLogParser)
    {
      try cdcMethodCheckAndSet(.binaryLogParser(binaryLogParser))
    }
    self.cdcMethod = cdcMethod
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.includeObjects, forKey: .includeObjects)
    try container.encode(self.excludeObjects, forKey: .excludeObjects)
    try container.encode(self.maxConcurrentCdcTasks, forKey: .maxConcurrentCdcTasks)
    try container.encode(self.maxConcurrentBackfillTasks, forKey: .maxConcurrentBackfillTasks)

    if let choice = self.largeObjectsHandling {
      switch choice {
      case .dropLargeObjects(let value):
        try container.encode(value, forKey: .dropLargeObjects)
      case .streamLargeObjects(let value):
        try container.encode(value, forKey: .streamLargeObjects)
      }
    }

    if let choice = self.cdcMethod {
      switch choice {
      case .logMiner(let value):
        try container.encode(value, forKey: .logMiner)
      case .binaryLogParser(let value):
        try container.encode(value, forKey: .binaryLogParser)
      }
    }
  }

  /// Configuration to drop large object values.
  public struct DropLargeObjects: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `DropLargeObjects`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = DropLargeObjects().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.DropLargeObjects"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to stream large object values.
  public struct StreamLargeObjects: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `StreamLargeObjects`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StreamLargeObjects().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.StreamLargeObjects"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to use LogMiner CDC method.
  public struct LogMiner: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Initialize a new instance of `LogMiner`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LogMiner().with { $0.<placeholder> = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.LogMiner"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration to use Binary Log Parser CDC technique.
  public struct BinaryLogParser: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Configuration to specify how the log file should be accessed.
    public var logFileAccess: OneOf_LogFileAccess? = nil

    /// Initialize a new instance of `BinaryLogParser`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = BinaryLogParser().with { $0.oracleAsmLogFileAccess = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private enum CodingKeys: Swift.String, CodingKey {
      case oracleAsmLogFileAccess = "oracleAsmLogFileAccess"
      case logFileDirectories = "logFileDirectories"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var logFileAccess: OneOf_LogFileAccess? = nil
      let logFileAccessCheckAndSet = {
        if logFileAccess != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'logFileAccess'"))
        }
        logFileAccess = $0
      }
      if let oracleAsmLogFileAccess = try container.decodeIfPresent(
        OracleSourceConfig.BinaryLogParser.OracleAsmLogFileAccess?.self,
        forKey: .oracleAsmLogFileAccess)
      {
        try logFileAccessCheckAndSet(.oracleAsmLogFileAccess(oracleAsmLogFileAccess))
      }
      if let logFileDirectories = try container.decodeIfPresent(
        OracleSourceConfig.BinaryLogParser.LogFileDirectories?.self, forKey: .logFileDirectories)
      {
        try logFileAccessCheckAndSet(.logFileDirectories(logFileDirectories))
      }
      self.logFileAccess = logFileAccess
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.logFileAccess {
        switch choice {
        case .oracleAsmLogFileAccess(let value):
          try container.encode(value, forKey: .oracleAsmLogFileAccess)
        case .logFileDirectories(let value):
          try container.encode(value, forKey: .logFileDirectories)
        }
      }
    }

    /// Configuration to use Oracle ASM to access the log files.
    public struct OracleAsmLogFileAccess: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `OracleAsmLogFileAccess`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = OracleAsmLogFileAccess().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.BinaryLogParser.OracleAsmLogFileAccess"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration to specify the Oracle directories to access the log files.
    public struct LogFileDirectories: Codable, Equatable, GoogleCloudWKT._AnyPackable,
      Sendable
    {
      /// Required. Oracle directory for online logs.
      public var onlineLogDirectory: Swift.String = Swift.String()

      /// Required. Oracle directory for archived logs.
      public var archivedLogDirectory: Swift.String = Swift.String()

      /// Initialize a new instance of `LogFileDirectories`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = LogFileDirectories().with { $0.onlineLogDirectory = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.BinaryLogParser.LogFileDirectories"
      }
      public init(fromAny any: GoogleCloudWKT.`Any`) throws {
        self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWKT.Struct {
        return try GoogleCloudWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration to specify how the log file should be accessed.
    public enum OneOf_LogFileAccess: Codable, Equatable, Sendable {
      /// Use Oracle ASM.
      indirect case oracleAsmLogFileAccess(
        OracleSourceConfig.BinaryLogParser.OracleAsmLogFileAccess?)
      /// Use Oracle directories.
      indirect case logFileDirectories(OracleSourceConfig.BinaryLogParser.LogFileDirectories?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig.BinaryLogParser"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// The configuration for handle Oracle large objects.
  public enum OneOf_LargeObjectsHandling: Codable, Equatable, Sendable {
    /// Drop large object values.
    indirect case dropLargeObjects(OracleSourceConfig.DropLargeObjects?)
    /// Stream large object values.
    indirect case streamLargeObjects(OracleSourceConfig.StreamLargeObjects?)
  }

  /// Configuration to select the CDC method.
  public enum OneOf_CdcMethod: Codable, Equatable, Sendable {
    /// Use LogMiner.
    indirect case logMiner(OracleSourceConfig.LogMiner?)
    /// Use Binary Log Parser.
    indirect case binaryLogParser(OracleSourceConfig.BinaryLogParser?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.OracleSourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
