// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Configuration for Oracle Automatic Storage Management (ASM) connection.
public struct OracleAsmConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. Hostname for the Oracle ASM connection.
  public var hostname: Swift.String = Swift.String()

  /// Required. Port for the Oracle ASM connection.
  public var port: Swift.Int32 = Swift.Int32()

  /// Required. Username for the Oracle ASM connection.
  public var username: Swift.String = Swift.String()

  /// Optional. Password for the Oracle ASM connection. Mutually exclusive with
  /// the `secret_manager_stored_password` field.
  public var password: Swift.String = Swift.String()

  /// Required. ASM service name for the Oracle ASM connection.
  public var asmService: Swift.String = Swift.String()

  /// Optional. Connection string attributes
  public var connectionAttributes: [Swift.String: Swift.String] = [:]

  /// Optional. SSL configuration for the Oracle connection.
  public var oracleSslConfig: OracleSslConfig? = nil

  /// Optional. A reference to a Secret Manager resource name storing the Oracle
  /// ASM connection password. Mutually exclusive with the `password` field.
  public var secretManagerStoredPassword: Swift.String = Swift.String()

  /// Initialize a new instance of `OracleAsmConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OracleAsmConfig().with { $0.hostname = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.OracleAsmConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
