// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Oracle database profile.
public struct OracleProfile: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. Hostname for the Oracle connection.
  public var hostname: Swift.String = Swift.String()

  /// Port for the Oracle connection, default value is 1521.
  public var port: Swift.Int32 = Swift.Int32()

  /// Required. Username for the Oracle connection.
  public var username: Swift.String = Swift.String()

  /// Optional. Password for the Oracle connection. Mutually exclusive with the
  /// `secret_manager_stored_password` field.
  public var password: Swift.String = Swift.String()

  /// Required. Database for the Oracle connection.
  public var databaseService: Swift.String = Swift.String()

  /// Connection string attributes
  public var connectionAttributes: [Swift.String: Swift.String] = [:]

  /// Optional. SSL configuration for the Oracle connection.
  public var oracleSslConfig: OracleSslConfig? = nil

  /// Optional. Configuration for Oracle ASM connection.
  public var oracleAsmConfig: OracleAsmConfig? = nil

  /// Optional. A reference to a Secret Manager resource name storing the Oracle
  /// connection password. Mutually exclusive with the `password` field.
  public var secretManagerStoredPassword: Swift.String = Swift.String()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OracleProfile`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OracleProfile().with { $0.hostname = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let hostname = CodingKeys(stringValue: "hostname")
    static let port = CodingKeys(stringValue: "port")
    static let username = CodingKeys(stringValue: "username")
    static let password = CodingKeys(stringValue: "password")
    static let databaseService = CodingKeys(stringValue: "databaseService")
    static let connectionAttributes = CodingKeys(stringValue: "connectionAttributes")
    static let oracleSslConfig = CodingKeys(stringValue: "oracleSslConfig")
    static let oracleAsmConfig = CodingKeys(stringValue: "oracleAsmConfig")
    static let secretManagerStoredPassword = CodingKeys(stringValue: "secretManagerStoredPassword")

    static let _knownKeys: Set<Swift.String> = [
      "hostname",
      "port",
      "username",
      "password",
      "databaseService",
      "connectionAttributes",
      "oracleSslConfig",
      "oracleAsmConfig",
      "secretManagerStoredPassword",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .hostname) {
      self.hostname = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .username) {
      self.username = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .password) {
      self.password = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .databaseService) {
      self.databaseService = value
    }
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .connectionAttributes)
    {
      self.connectionAttributes = value
    }
    self.oracleSslConfig = try container.decodeIfPresent(
      OracleSslConfig.self, forKey: .oracleSslConfig)
    self.oracleAsmConfig = try container.decodeIfPresent(
      OracleAsmConfig.self, forKey: .oracleAsmConfig)
    if let value = try container.decodeIfPresent(
      Swift.String.self, forKey: .secretManagerStoredPassword)
    {
      self.secretManagerStoredPassword = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.hostname, forKey: .hostname)
    try container.encode(self.port, forKey: .port)
    try container.encode(self.username, forKey: .username)
    try container.encode(self.password, forKey: .password)
    try container.encode(self.databaseService, forKey: .databaseService)
    try container.encode(self.connectionAttributes, forKey: .connectionAttributes)
    try container.encodeIfPresent(self.oracleSslConfig, forKey: .oracleSslConfig)
    try container.encodeIfPresent(self.oracleAsmConfig, forKey: .oracleAsmConfig)
    try container.encode(self.secretManagerStoredPassword, forKey: .secretManagerStoredPassword)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.OracleProfile"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
