// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// PostgreSQL SSL configuration information.
public struct PostgresqlSslConfig: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The encryption settings available for PostgreSQL connection profiles.
  /// This captures various SSL mode supported by PostgreSQL, which includes
  /// TLS encryption with server verification, TLS encryption with both server
  /// and client verification and no TLS encryption.
  public var encryptionSetting: EncryptionSettingOneOf? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `PostgresqlSslConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PostgresqlSslConfig().with { $0.serverVerification = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let serverVerification = CodingKeys(stringValue: "serverVerification")
    static let serverAndClientVerification = CodingKeys(stringValue: "serverAndClientVerification")

    static let _knownKeys: Set<Swift.String> = [
      "serverVerification",
      "serverAndClientVerification",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)

    var encryptionSetting: EncryptionSettingOneOf? = nil
    let encryptionSettingCheckAndSet = {
      if encryptionSetting != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'encryptionSetting'"))
      }
      encryptionSetting = $0
    }
    if let serverVerification = try container.decodeIfPresent(
      PostgresqlSslConfig.ServerVerification?.self, forKey: .serverVerification)
    {
      try encryptionSettingCheckAndSet(.serverVerification(serverVerification))
    }
    if let serverAndClientVerification = try container.decodeIfPresent(
      PostgresqlSslConfig.ServerAndClientVerification?.self, forKey: .serverAndClientVerification)
    {
      try encryptionSettingCheckAndSet(.serverAndClientVerification(serverAndClientVerification))
    }
    self.encryptionSetting = encryptionSetting
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)

    if let choice = self.encryptionSetting {
      switch choice {
      case .serverVerification(let value):
        try container.encode(value, forKey: .serverVerification)
      case .serverAndClientVerification(let value):
        try container.encode(value, forKey: .serverAndClientVerification)
      }
    }
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Message represents the option where Datastream will enforce the encryption
  /// and authenticate the server identity. ca_certificate must be set if user
  /// selects this option.
  public struct ServerVerification: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Input only. PEM-encoded server root CA certificate.
    public var caCertificate: Swift.String = Swift.String()

    /// Optional. The hostname mentioned in the Subject or SAN extension of the
    /// server certificate. If this field is not provided, the hostname in the
    /// server certificate is not validated.
    public var serverCertificateHostname: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ServerVerification`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ServerVerification().with { $0.caCertificate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let caCertificate = CodingKeys(stringValue: "caCertificate")
      static let serverCertificateHostname = CodingKeys(stringValue: "serverCertificateHostname")

      static let _knownKeys: Set<Swift.String> = [
        "caCertificate",
        "serverCertificateHostname",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .caCertificate) {
        self.caCertificate = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .serverCertificateHostname)
      {
        self.serverCertificateHostname = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.caCertificate, forKey: .caCertificate)
      try container.encode(self.serverCertificateHostname, forKey: .serverCertificateHostname)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.datastream.v1.PostgresqlSslConfig.ServerVerification"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Message represents the option where Datastream will enforce the encryption
  /// and authenticate the server identity as well as the client identity.
  /// ca_certificate, client_certificate and client_key must be set if user
  /// selects this option.
  public struct ServerAndClientVerification: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Required. Input only. PEM-encoded certificate used by the source database
    /// to authenticate the client identity (i.e., the Datastream's identity).
    /// This certificate is signed by either a root certificate trusted by the
    /// server or one or more intermediate certificates (which is stored with the
    /// leaf certificate) to link the this certificate to the trusted root
    /// certificate.
    public var clientCertificate: Swift.String = Swift.String()

    /// Optional. Input only. PEM-encoded private key associated with the client
    /// certificate. This value will be used during the SSL/TLS handshake,
    /// allowing the PostgreSQL server to authenticate the client's identity,
    /// i.e. identity of the Datastream.
    public var clientKey: Swift.String = Swift.String()

    /// Required. Input only. PEM-encoded server root CA certificate.
    public var caCertificate: Swift.String = Swift.String()

    /// Optional. The hostname mentioned in the Subject or SAN extension of the
    /// server certificate. If this field is not provided, the hostname in the
    /// server certificate is not validated.
    public var serverCertificateHostname: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ServerAndClientVerification`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ServerAndClientVerification().with { $0.clientCertificate = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let clientCertificate = CodingKeys(stringValue: "clientCertificate")
      static let clientKey = CodingKeys(stringValue: "clientKey")
      static let caCertificate = CodingKeys(stringValue: "caCertificate")
      static let serverCertificateHostname = CodingKeys(stringValue: "serverCertificateHostname")

      static let _knownKeys: Set<Swift.String> = [
        "clientCertificate",
        "clientKey",
        "caCertificate",
        "serverCertificateHostname",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientCertificate) {
        self.clientCertificate = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clientKey) {
        self.clientKey = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .caCertificate) {
        self.caCertificate = value
      }
      if let value = try container.decodeIfPresent(
        Swift.String.self, forKey: .serverCertificateHostname)
      {
        self.serverCertificateHostname = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.clientCertificate, forKey: .clientCertificate)
      try container.encode(self.clientKey, forKey: .clientKey)
      try container.encode(self.caCertificate, forKey: .caCertificate)
      try container.encode(self.serverCertificateHostname, forKey: .serverCertificateHostname)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.datastream.v1.PostgresqlSslConfig.ServerAndClientVerification"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The encryption settings available for PostgreSQL connection profiles.
  /// This captures various SSL mode supported by PostgreSQL, which includes
  /// TLS encryption with server verification, TLS encryption with both server
  /// and client verification and no TLS encryption.
  public enum EncryptionSettingOneOf: Codable, Equatable, Sendable {
    ///  If this field is set, the communication will be encrypted with TLS
    ///  encryption and the server identity will be authenticated.
    indirect case serverVerification(PostgresqlSslConfig.ServerVerification?)
    /// If this field is set, the communication will be encrypted with TLS
    /// encryption and both the server identity and the client identity will be
    /// authenticated.
    indirect case serverAndClientVerification(PostgresqlSslConfig.ServerAndClientVerification?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.PostgresqlSslConfig"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
