// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// PostgreSQL data source configuration
public struct PostgresqlSourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// PostgreSQL objects to include in the stream.
  public var includeObjects: PostgresqlRdbms? = nil

  /// PostgreSQL objects to exclude from the stream.
  public var excludeObjects: PostgresqlRdbms? = nil

  /// Required. Immutable. The name of the logical replication slot that's
  /// configured with the pgoutput plugin.
  public var replicationSlot: Swift.String = Swift.String()

  /// Required. The name of the publication that includes the set of all tables
  /// that are defined in the stream's include_objects.
  public var publication: Swift.String = Swift.String()

  /// Maximum number of concurrent backfill tasks. The number should be non
  /// negative. If not set (or set to 0), the system's default value will be
  /// used.
  public var maxConcurrentBackfillTasks: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `PostgresqlSourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PostgresqlSourceConfig().with { $0.includeObjects = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.PostgresqlSourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
