// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// PostgreSQL data source configuration
public struct PostgresqlSourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// PostgreSQL objects to include in the stream.
  public var includeObjects: PostgresqlRdbms? = nil

  /// PostgreSQL objects to exclude from the stream.
  public var excludeObjects: PostgresqlRdbms? = nil

  /// Required. Immutable. The name of the logical replication slot that's
  /// configured with the pgoutput plugin.
  public var replicationSlot: Swift.String = Swift.String()

  /// Required. The name of the publication that includes the set of all tables
  /// that are defined in the stream's include_objects.
  public var publication: Swift.String = Swift.String()

  /// Maximum number of concurrent backfill tasks. The number should be non
  /// negative. If not set (or set to 0), the system's default value will be
  /// used.
  public var maxConcurrentBackfillTasks: Swift.Int32 = Swift.Int32()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleCloudWKT._UnknownFields = .init()

  /// Initialize a new instance of `PostgresqlSourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PostgresqlSourceConfig().with { $0.includeObjects = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let includeObjects = CodingKeys(stringValue: "includeObjects")
    static let excludeObjects = CodingKeys(stringValue: "excludeObjects")
    static let replicationSlot = CodingKeys(stringValue: "replicationSlot")
    static let publication = CodingKeys(stringValue: "publication")
    static let maxConcurrentBackfillTasks = CodingKeys(stringValue: "maxConcurrentBackfillTasks")

    static let _knownKeys: Set<Swift.String> = [
      "includeObjects",
      "excludeObjects",
      "replicationSlot",
      "publication",
      "maxConcurrentBackfillTasks",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.includeObjects = try container.decodeIfPresent(
      PostgresqlRdbms.self, forKey: .includeObjects)
    self.excludeObjects = try container.decodeIfPresent(
      PostgresqlRdbms.self, forKey: .excludeObjects)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .replicationSlot) {
      self.replicationSlot = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .publication) {
      self.publication = value
    }
    if let value = try container.decodeIfPresent(
      Swift.Int32.self, forKey: .maxConcurrentBackfillTasks)
    {
      self.maxConcurrentBackfillTasks = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleCloudWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.includeObjects, forKey: .includeObjects)
    try container.encodeIfPresent(self.excludeObjects, forKey: .excludeObjects)
    try container.encode(self.replicationSlot, forKey: .replicationSlot)
    try container.encode(self.publication, forKey: .publication)
    try container.encode(self.maxConcurrentBackfillTasks, forKey: .maxConcurrentBackfillTasks)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.PostgresqlSourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
