// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The PrivateConnection resource is used to establish private connectivity
/// between Datastream and a customer's network.
public struct PrivateConnection: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource's name.
  public var name: Swift.String = Swift.String()

  /// Output only. The create time of the resource.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The update time of the resource.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Output only. The state of the Private Connection.
  public var state: PrivateConnection.State = PrivateConnection.State()

  /// Output only. In case of error, the details of the error in a user-friendly
  /// format.
  public var error: Error? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzs: Swift.Bool? = nil

  /// Output only. Reserved for future use.
  public var satisfiesPzi: Swift.Bool? = nil

  /// VPC Peering Config.
  public var vpcPeeringConfig: VpcPeeringConfig? = nil

  /// PSC Interface Config.
  public var pscInterfaceConfig: PscInterfaceConfig? = nil

  /// Initialize a new instance of `PrivateConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = PrivateConnection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Private Connection state.
  public enum State: Codable, Equatable, Sendable {
    /// Unspecified state.
    case unspecified
    /// The private connection is in creation state - creating resources.
    case creating
    /// The private connection has been created with all of its resources.
    case created
    /// The private connection creation has failed.
    case failed
    /// The private connection is being deleted.
    case deleting
    /// Delete request has failed, resource is in invalid state.
    case failedToDelete
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .creating: return 1
      case .created: return 2
      case .failed: return 3
      case .deleting: return 4
      case .failedToDelete: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATE_UNSPECIFIED"
      case .creating: return "CREATING"
      case .created: return "CREATED"
      case .failed: return "FAILED"
      case .deleting: return "DELETING"
      case .failedToDelete: return "FAILED_TO_DELETE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATE_UNSPECIFIED": self = .unspecified
      case "CREATING": self = .creating
      case "CREATED": self = .created
      case "FAILED": self = .failed
      case "DELETING": self = .deleting
      case "FAILED_TO_DELETE": self = .failedToDelete
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .creating
      case 2: self = .created
      case 3: self = .failed
      case 4: self = .deleting
      case 5: self = .failedToDelete
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .creating: return try container.encode(1)
      case .created: return try container.encode(2)
      case .failed: return try container.encode(3)
      case .deleting: return try container.encode(4)
      case .failedToDelete: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.PrivateConnection"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
