// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// The route resource is the child of the private connection resource,
/// used for defining a route for a private connection.
public struct Route: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The resource's name.
  public var name: Swift.String = Swift.String()

  /// Output only. The create time of the resource.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The update time of the resource.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Labels.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Required. Destination address for connection
  public var destinationAddress: Swift.String = Swift.String()

  /// Destination port for connection
  public var destinationPort: Swift.Int32 = Swift.Int32()

  /// Initialize a new instance of `Route`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Route().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.Route"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
