// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Salesforce source configuration
public struct SalesforceSourceConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Salesforce objects to retrieve from the source.
  public var includeObjects: SalesforceOrg? = nil

  /// Salesforce objects to exclude from the stream.
  public var excludeObjects: SalesforceOrg? = nil

  /// Required. Salesforce objects polling interval. The interval at which new
  /// changes will be polled for each object. The duration must be between 5
  /// minutes and 24 hours.
  public var pollingInterval: GoogleCloudWKT.Duration? = nil

  /// Initialize a new instance of `SalesforceSourceConfig`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = SalesforceSourceConfig().with { $0.includeObjects = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.SalesforceSourceConfig"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
