// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// A specific stream object (e.g a specific DB table).
public struct StreamObject: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Identifier. The object resource's name.
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time of the object.
  public var createTime: GoogleCloudWkt.Timestamp? = nil

  /// Output only. The last update time of the object.
  public var updateTime: GoogleCloudWkt.Timestamp? = nil

  /// Required. Display name.
  public var displayName: Swift.String = Swift.String()

  /// Output only. Active errors on the object.
  public var errors: [Error] = []

  /// The latest backfill job that was initiated for the stream object.
  public var backfillJob: BackfillJob? = nil

  /// The object identifier in the data source.
  public var sourceObject: SourceObjectIdentifier? = nil

  /// Initialize a new instance of `StreamObject`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = StreamObject().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.datastream.v1.StreamObject"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
